/*
 * This file is generated by jOOQ.
 */
package com.litdeck.backend.jooq.tables.records;


import com.litdeck.backend.jooq.tables.DeckProblems;
import com.litdeck.backend.jooq.tables.pojos.DeckProblemspojo;

import jakarta.validation.constraints.NotNull;

import java.time.LocalDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DeckProblemsRecord extends UpdatableRecordImpl<DeckProblemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>litdeck.deck_problems.deck_id</code>.
     */
    public DeckProblemsRecord setDeckId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.deck_problems.deck_id</code>.
     */
    @NotNull
    public Integer getDeckId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>litdeck.deck_problems.problem_id</code>.
     */
    public DeckProblemsRecord setProblemId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.deck_problems.problem_id</code>.
     */
    @NotNull
    public Integer getProblemId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>litdeck.deck_problems.added_at</code>.
     */
    public DeckProblemsRecord setAddedAt(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.deck_problems.added_at</code>.
     */
    public LocalDateTime getAddedAt() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DeckProblemsRecord
     */
    public DeckProblemsRecord() {
        super(DeckProblems.DECK_PROBLEMS);
    }

    /**
     * Create a detached, initialised DeckProblemsRecord
     */
    public DeckProblemsRecord(Integer deckId, Integer problemId, LocalDateTime addedAt) {
        super(DeckProblems.DECK_PROBLEMS);

        setDeckId(deckId);
        setProblemId(problemId);
        setAddedAt(addedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised DeckProblemsRecord
     */
    public DeckProblemsRecord(DeckProblemspojo value) {
        super(DeckProblems.DECK_PROBLEMS);

        if (value != null) {
            setDeckId(value.getDeckId());
            setProblemId(value.getProblemId());
            setAddedAt(value.getAddedAt());
            resetChangedOnNotNull();
        }
    }
}
