/*
 * This file is generated by jOOQ.
 */
package com.litdeck.backend.jooq.tables.records;


import com.litdeck.backend.jooq.tables.Decks;
import com.litdeck.backend.jooq.tables.pojos.Deckspojo;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DecksRecord extends UpdatableRecordImpl<DecksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>litdeck.decks.id</code>.
     */
    public DecksRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.decks.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>litdeck.decks.user_id</code>.
     */
    public DecksRecord setUserId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.decks.user_id</code>.
     */
    @NotNull
    @Size(max = 36)
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>litdeck.decks.name</code>.
     */
    public DecksRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.decks.name</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>litdeck.decks.description</code>.
     */
    public DecksRecord setDescription(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.decks.description</code>.
     */
    @Size(max = 65535)
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>litdeck.decks.is_public</code>.
     */
    public DecksRecord setIsPublic(Byte value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.decks.is_public</code>.
     */
    public Byte getIsPublic() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>litdeck.decks.created_at</code>.
     */
    public DecksRecord setCreatedAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.decks.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>litdeck.decks.updated_at</code>.
     */
    public DecksRecord setUpdatedAt(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.decks.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DecksRecord
     */
    public DecksRecord() {
        super(Decks.DECKS);
    }

    /**
     * Create a detached, initialised DecksRecord
     */
    public DecksRecord(Integer id, String userId, String name, String description, Byte isPublic, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Decks.DECKS);

        setId(id);
        setUserId(userId);
        setName(name);
        setDescription(description);
        setIsPublic(isPublic);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised DecksRecord
     */
    public DecksRecord(Deckspojo value) {
        super(Decks.DECKS);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setName(value.getName());
            setDescription(value.getDescription());
            setIsPublic(value.getIsPublic());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
