/*
 * This file is generated by jOOQ.
 */
package com.litdeck.backend.jooq.tables.records;


import com.litdeck.backend.jooq.tables.FlashcardReviews;
import com.litdeck.backend.jooq.tables.pojos.FlashcardReviewspojo;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FlashcardReviewsRecord extends UpdatableRecordImpl<FlashcardReviewsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>litdeck.flashcard_reviews.id</code>.
     */
    public FlashcardReviewsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.flashcard_reviews.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>litdeck.flashcard_reviews.user_id</code>.
     */
    public FlashcardReviewsRecord setUserId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.flashcard_reviews.user_id</code>.
     */
    @NotNull
    @Size(max = 36)
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>litdeck.flashcard_reviews.deck_id</code>.
     */
    public FlashcardReviewsRecord setDeckId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.flashcard_reviews.deck_id</code>.
     */
    @NotNull
    public Integer getDeckId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>litdeck.flashcard_reviews.problem_id</code>.
     */
    public FlashcardReviewsRecord setProblemId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.flashcard_reviews.problem_id</code>.
     */
    @NotNull
    public Integer getProblemId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>litdeck.flashcard_reviews.due_date</code>.
     */
    public FlashcardReviewsRecord setDueDate(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.flashcard_reviews.due_date</code>.
     */
    @NotNull
    public LocalDateTime getDueDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>litdeck.flashcard_reviews.stability</code>.
     */
    public FlashcardReviewsRecord setStability(Double value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.flashcard_reviews.stability</code>.
     */
    public Double getStability() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>litdeck.flashcard_reviews.difficulty</code>.
     */
    public FlashcardReviewsRecord setDifficulty(Double value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.flashcard_reviews.difficulty</code>.
     */
    public Double getDifficulty() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>litdeck.flashcard_reviews.elapsed_days</code>.
     */
    public FlashcardReviewsRecord setElapsedDays(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.flashcard_reviews.elapsed_days</code>.
     */
    public Integer getElapsedDays() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>litdeck.flashcard_reviews.scheduled_days</code>.
     */
    public FlashcardReviewsRecord setScheduledDays(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.flashcard_reviews.scheduled_days</code>.
     */
    public Integer getScheduledDays() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>litdeck.flashcard_reviews.reps</code>.
     */
    public FlashcardReviewsRecord setReps(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.flashcard_reviews.reps</code>.
     */
    public Integer getReps() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>litdeck.flashcard_reviews.lapses</code>.
     */
    public FlashcardReviewsRecord setLapses(Integer value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.flashcard_reviews.lapses</code>.
     */
    public Integer getLapses() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>litdeck.flashcard_reviews.state</code>.
     */
    public FlashcardReviewsRecord setState(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.flashcard_reviews.state</code>.
     */
    @Size(max = 50)
    public String getState() {
        return (String) get(11);
    }

    /**
     * Setter for <code>litdeck.flashcard_reviews.last_review</code>.
     */
    public FlashcardReviewsRecord setLastReview(LocalDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.flashcard_reviews.last_review</code>.
     */
    public LocalDateTime getLastReview() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>litdeck.flashcard_reviews.created_at</code>.
     */
    public FlashcardReviewsRecord setCreatedAt(LocalDateTime value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.flashcard_reviews.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>litdeck.flashcard_reviews.updated_at</code>.
     */
    public FlashcardReviewsRecord setUpdatedAt(LocalDateTime value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.flashcard_reviews.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FlashcardReviewsRecord
     */
    public FlashcardReviewsRecord() {
        super(FlashcardReviews.FLASHCARD_REVIEWS);
    }

    /**
     * Create a detached, initialised FlashcardReviewsRecord
     */
    public FlashcardReviewsRecord(Integer id, String userId, Integer deckId, Integer problemId, LocalDateTime dueDate, Double stability, Double difficulty, Integer elapsedDays, Integer scheduledDays, Integer reps, Integer lapses, String state, LocalDateTime lastReview, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(FlashcardReviews.FLASHCARD_REVIEWS);

        setId(id);
        setUserId(userId);
        setDeckId(deckId);
        setProblemId(problemId);
        setDueDate(dueDate);
        setStability(stability);
        setDifficulty(difficulty);
        setElapsedDays(elapsedDays);
        setScheduledDays(scheduledDays);
        setReps(reps);
        setLapses(lapses);
        setState(state);
        setLastReview(lastReview);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised FlashcardReviewsRecord
     */
    public FlashcardReviewsRecord(FlashcardReviewspojo value) {
        super(FlashcardReviews.FLASHCARD_REVIEWS);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setDeckId(value.getDeckId());
            setProblemId(value.getProblemId());
            setDueDate(value.getDueDate());
            setStability(value.getStability());
            setDifficulty(value.getDifficulty());
            setElapsedDays(value.getElapsedDays());
            setScheduledDays(value.getScheduledDays());
            setReps(value.getReps());
            setLapses(value.getLapses());
            setState(value.getState());
            setLastReview(value.getLastReview());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
