/*
 * This file is generated by jOOQ.
 */
package com.litdeck.backend.jooq.tables.records;


import com.litdeck.backend.jooq.tables.ProblemsTopic;
import com.litdeck.backend.jooq.tables.pojos.ProblemsTopicpojo;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProblemsTopicRecord extends UpdatableRecordImpl<ProblemsTopicRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>litdeck.problems_topic.problem_id</code>.
     */
    public ProblemsTopicRecord setProblemId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.problems_topic.problem_id</code>.
     */
    @NotNull
    public Integer getProblemId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>litdeck.problems_topic.topic_slug</code>.
     */
    public ProblemsTopicRecord setTopicSlug(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.problems_topic.topic_slug</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getTopicSlug() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProblemsTopicRecord
     */
    public ProblemsTopicRecord() {
        super(ProblemsTopic.PROBLEMS_TOPIC);
    }

    /**
     * Create a detached, initialised ProblemsTopicRecord
     */
    public ProblemsTopicRecord(Integer problemId, String topicSlug) {
        super(ProblemsTopic.PROBLEMS_TOPIC);

        setProblemId(problemId);
        setTopicSlug(topicSlug);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ProblemsTopicRecord
     */
    public ProblemsTopicRecord(ProblemsTopicpojo value) {
        super(ProblemsTopic.PROBLEMS_TOPIC);

        if (value != null) {
            setProblemId(value.getProblemId());
            setTopicSlug(value.getTopicSlug());
            resetChangedOnNotNull();
        }
    }
}
