/*
 * This file is generated by jOOQ.
 */
package com.litdeck.backend.jooq.tables.records;


import com.litdeck.backend.jooq.tables.Problems;
import com.litdeck.backend.jooq.tables.pojos.Problemspojo;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;

import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProblemsRecord extends UpdatableRecordImpl<ProblemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>litdeck.problems.id</code>.
     */
    public ProblemsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.problems.id</code>.
     */
    @NotNull
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>litdeck.problems.frontend_id</code>.
     */
    public ProblemsRecord setFrontendId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.problems.frontend_id</code>.
     */
    @NotNull
    public Integer getFrontendId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>litdeck.problems.title</code>.
     */
    public ProblemsRecord setTitle(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.problems.title</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>litdeck.problems.title_slug</code>.
     */
    public ProblemsRecord setTitleSlug(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.problems.title_slug</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getTitleSlug() {
        return (String) get(3);
    }

    /**
     * Setter for <code>litdeck.problems.difficulty</code>.
     */
    public ProblemsRecord setDifficulty(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.problems.difficulty</code>.
     */
    @NotNull
    @Size(max = 50)
    public String getDifficulty() {
        return (String) get(4);
    }

    /**
     * Setter for <code>litdeck.problems.is_paid_only</code>.
     */
    public ProblemsRecord setIsPaidOnly(Byte value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.problems.is_paid_only</code>.
     */
    @NotNull
    public Byte getIsPaidOnly() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>litdeck.problems.content</code>.
     */
    public ProblemsRecord setContent(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.problems.content</code>.
     */
    @NotNull
    @Size(max = 65535)
    public String getContent() {
        return (String) get(6);
    }

    /**
     * Setter for <code>litdeck.problems.topic_tags</code>.
     */
    public ProblemsRecord setTopicTags(JSON value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.problems.topic_tags</code>.
     */
    public JSON getTopicTags() {
        return (JSON) get(7);
    }

    /**
     * Setter for <code>litdeck.problems.example_testcases</code>.
     */
    public ProblemsRecord setExampleTestcases(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.problems.example_testcases</code>.
     */
    @Size(max = 65535)
    public String getExampleTestcases() {
        return (String) get(8);
    }

    /**
     * Setter for <code>litdeck.problems.similar_questions</code>.
     */
    public ProblemsRecord setSimilarQuestions(JSON value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.problems.similar_questions</code>.
     */
    public JSON getSimilarQuestions() {
        return (JSON) get(9);
    }

    /**
     * Setter for <code>litdeck.problems.created_at</code>.
     */
    public ProblemsRecord setCreatedAt(LocalDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.problems.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProblemsRecord
     */
    public ProblemsRecord() {
        super(Problems.PROBLEMS);
    }

    /**
     * Create a detached, initialised ProblemsRecord
     */
    public ProblemsRecord(Integer id, Integer frontendId, String title, String titleSlug, String difficulty, Byte isPaidOnly, String content, JSON topicTags, String exampleTestcases, JSON similarQuestions, LocalDateTime createdAt) {
        super(Problems.PROBLEMS);

        setId(id);
        setFrontendId(frontendId);
        setTitle(title);
        setTitleSlug(titleSlug);
        setDifficulty(difficulty);
        setIsPaidOnly(isPaidOnly);
        setContent(content);
        setTopicTags(topicTags);
        setExampleTestcases(exampleTestcases);
        setSimilarQuestions(similarQuestions);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ProblemsRecord
     */
    public ProblemsRecord(Problemspojo value) {
        super(Problems.PROBLEMS);

        if (value != null) {
            setId(value.getId());
            setFrontendId(value.getFrontendId());
            setTitle(value.getTitle());
            setTitleSlug(value.getTitleSlug());
            setDifficulty(value.getDifficulty());
            setIsPaidOnly(value.getIsPaidOnly());
            setContent(value.getContent());
            setTopicTags(value.getTopicTags());
            setExampleTestcases(value.getExampleTestcases());
            setSimilarQuestions(value.getSimilarQuestions());
            setCreatedAt(value.getCreatedAt());
            resetChangedOnNotNull();
        }
    }
}
