/*
 * This file is generated by jOOQ.
 */
package com.litdeck.backend.jooq.tables.records;


import com.litdeck.backend.jooq.tables.Users;
import com.litdeck.backend.jooq.tables.pojos.Userspojo;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>litdeck.users.id</code>.
     */
    public UsersRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.users.id</code>.
     */
    @Size(max = 36)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>litdeck.users.email</code>.
     */
    public UsersRecord setEmail(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.users.email</code>.
     */
    @Size(max = 255)
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>litdeck.users.username</code>.
     */
    public UsersRecord setUsername(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.users.username</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>litdeck.users.created_at</code>.
     */
    public UsersRecord setCreatedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.users.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>litdeck.users.leetcode_username</code>.
     */
    public UsersRecord setLeetcodeUsername(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.users.leetcode_username</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getLeetcodeUsername() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(String id, String email, String username, LocalDateTime createdAt, String leetcodeUsername) {
        super(Users.USERS);

        setId(id);
        setEmail(email);
        setUsername(username);
        setCreatedAt(createdAt);
        setLeetcodeUsername(leetcodeUsername);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Userspojo value) {
        super(Users.USERS);

        if (value != null) {
            setId(value.getId());
            setEmail(value.getEmail());
            setUsername(value.getUsername());
            setCreatedAt(value.getCreatedAt());
            setLeetcodeUsername(value.getLeetcodeUsername());
            resetChangedOnNotNull();
        }
    }
}
