/*
 * This file is generated by jOOQ.
 */
package com.ls.jooq.tables.records;


import com.ls.jooq.tables.UserApiKey;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserApiKeyRecord extends UpdatableRecordImpl<UserApiKeyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>leetstack.user_api_key.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>leetstack.user_api_key.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>leetstack.user_api_key.user_id</code>.
     */
    public void setUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>leetstack.user_api_key.user_id</code>.
     */
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>leetstack.user_api_key.key_hash</code>.
     */
    public void setKeyHash(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>leetstack.user_api_key.key_hash</code>.
     */
    public String getKeyHash() {
        return (String) get(2);
    }

    /**
     * Setter for <code>leetstack.user_api_key.label</code>.
     */
    public void setLabel(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>leetstack.user_api_key.label</code>.
     */
    public String getLabel() {
        return (String) get(3);
    }

    /**
     * Setter for <code>leetstack.user_api_key.revoked</code>.
     */
    public void setRevoked(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>leetstack.user_api_key.revoked</code>.
     */
    public Byte getRevoked() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>leetstack.user_api_key.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>leetstack.user_api_key.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>leetstack.user_api_key.last_used_date</code>.
     */
    public void setLastUsedDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>leetstack.user_api_key.last_used_date</code>.
     */
    public LocalDateTime getLastUsedDate() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserApiKeyRecord
     */
    public UserApiKeyRecord() {
        super(UserApiKey.USER_API_KEY);
    }

    /**
     * Create a detached, initialised UserApiKeyRecord
     */
    public UserApiKeyRecord(Long id, String userId, String keyHash, String label, Byte revoked, LocalDateTime createdDate, LocalDateTime lastUsedDate) {
        super(UserApiKey.USER_API_KEY);

        setId(id);
        setUserId(userId);
        setKeyHash(keyHash);
        setLabel(label);
        setRevoked(revoked);
        setCreatedDate(createdDate);
        setLastUsedDate(lastUsedDate);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised UserApiKeyRecord
     */
    public UserApiKeyRecord(com.ls.jooq.tables.pojos.UserApiKey value) {
        super(UserApiKey.USER_API_KEY);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setKeyHash(value.getKeyHash());
            setLabel(value.getLabel());
            setRevoked(value.getRevoked());
            setCreatedDate(value.getCreatedDate());
            setLastUsedDate(value.getLastUsedDate());
            resetTouchedOnNotNull();
        }
    }
}
