/*
 * This file is generated by jOOQ.
 */
package com.ls.jooq.tables.records;


import com.ls.jooq.tables.User;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>user.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>user.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>user.email</code>.
     */
    public void setEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>user.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>user.first_name</code>.
     */
    public void setFirstName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>user.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>user.last_name</code>.
     */
    public void setLastName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>user.last_name</code>.
     */
    public String getLastName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>user.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>user.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>user.last_updated_date</code>.
     */
    public void setLastUpdatedDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>user.last_updated_date</code>.
     */
    public LocalDateTime getLastUpdatedDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>user.leetstack_username</code>.
     */
    public void setLeetstackUsername(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>user.leetstack_username</code>.
     */
    public String getLeetstackUsername() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(String id, String email, String firstName, String lastName, LocalDateTime createdDate, LocalDateTime lastUpdatedDate, String leetstackUsername) {
        super(User.USER);

        setId(id);
        setEmail(email);
        setFirstName(firstName);
        setLastName(lastName);
        setCreatedDate(createdDate);
        setLastUpdatedDate(lastUpdatedDate);
        setLeetstackUsername(leetstackUsername);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(com.ls.jooq.tables.pojos.User value) {
        super(User.USER);

        if (value != null) {
            setId(value.getId());
            setEmail(value.getEmail());
            setFirstName(value.getFirstName());
            setLastName(value.getLastName());
            setCreatedDate(value.getCreatedDate());
            setLastUpdatedDate(value.getLastUpdatedDate());
            setLeetstackUsername(value.getLeetstackUsername());
            resetTouchedOnNotNull();
        }
    }
}
