/*
 * This file is generated by jOOQ.
 */
package com.ls.jooq.tables.records;


import com.ls.jooq.tables.Users;
import com.ls.jooq.tables.pojos.Userspojo;

import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>leetstack.users.id</code>.
     */
    public UsersRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>leetstack.users.id</code>.
     */
    @Size(max = 36)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>leetstack.users.email</code>.
     */
    public UsersRecord setEmail(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>leetstack.users.email</code>.
     */
    @Size(max = 255)
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>leetstack.users.first_name</code>.
     */
    public UsersRecord setFirstName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>leetstack.users.first_name</code>.
     */
    @Size(max = 100)
    public String getFirstName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>leetstack.users.last_name</code>.
     */
    public UsersRecord setLastName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>leetstack.users.last_name</code>.
     */
    @Size(max = 100)
    public String getLastName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>leetstack.users.created_date</code>.
     */
    public UsersRecord setCreatedDate(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>leetstack.users.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>leetstack.users.last_updated_date</code>.
     */
    public UsersRecord setLastUpdatedDate(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>leetstack.users.last_updated_date</code>.
     */
    public LocalDateTime getLastUpdatedDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>leetstack.users.leetstack_username</code>.
     */
    public UsersRecord setLeetstackUsername(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>leetstack.users.leetstack_username</code>.
     */
    @Size(max = 255)
    public String getLeetstackUsername() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(String id, String email, String firstName, String lastName, LocalDateTime createdDate, LocalDateTime lastUpdatedDate, String leetstackUsername) {
        super(Users.USERS);

        setId(id);
        setEmail(email);
        setFirstName(firstName);
        setLastName(lastName);
        setCreatedDate(createdDate);
        setLastUpdatedDate(lastUpdatedDate);
        setLeetstackUsername(leetstackUsername);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Userspojo value) {
        super(Users.USERS);

        if (value != null) {
            setId(value.getId());
            setEmail(value.getEmail());
            setFirstName(value.getFirstName());
            setLastName(value.getLastName());
            setCreatedDate(value.getCreatedDate());
            setLastUpdatedDate(value.getLastUpdatedDate());
            setLeetstackUsername(value.getLeetstackUsername());
            resetTouchedOnNotNull();
        }
    }
}
