/*
 * This file is generated by jOOQ.
 */
package com.ib.jooq.tables;


import com.ib.jooq.Indexes;
import com.ib.jooq.Keys;
import com.ib.jooq.Litdeck;
import com.ib.jooq.tables.DeckProblems.DeckProblemsPath;
import com.ib.jooq.tables.FlashcardReviews.FlashcardReviewsPath;
import com.ib.jooq.tables.Problems.ProblemsPath;
import com.ib.jooq.tables.Users.UsersPath;
import com.ib.jooq.tables.records.DecksRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Decks extends TableImpl<DecksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>litdeck.decks</code>
     */
    public static final Decks DECKS = new Decks();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DecksRecord> getRecordType() {
        return DecksRecord.class;
    }

    /**
     * The column <code>litdeck.decks.id</code>.
     */
    public final TableField<DecksRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>litdeck.decks.user_id</code>.
     */
    public final TableField<DecksRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.CHAR(36).nullable(false), this, "");

    /**
     * The column <code>litdeck.decks.name</code>.
     */
    public final TableField<DecksRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>litdeck.decks.description</code>.
     */
    public final TableField<DecksRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>litdeck.decks.is_public</code>.
     */
    public final TableField<DecksRecord, Byte> IS_PUBLIC = createField(DSL.name("is_public"), SQLDataType.TINYINT.defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>litdeck.decks.created_at</code>.
     */
    public final TableField<DecksRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>litdeck.decks.updated_at</code>.
     */
    public final TableField<DecksRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private Decks(Name alias, Table<DecksRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Decks(Name alias, Table<DecksRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>litdeck.decks</code> table reference
     */
    public Decks(String alias) {
        this(DSL.name(alias), DECKS);
    }

    /**
     * Create an aliased <code>litdeck.decks</code> table reference
     */
    public Decks(Name alias) {
        this(alias, DECKS);
    }

    /**
     * Create a <code>litdeck.decks</code> table reference
     */
    public Decks() {
        this(DSL.name("decks"), null);
    }

    public <O extends Record> Decks(Table<O> path, ForeignKey<O, DecksRecord> childPath, InverseForeignKey<O, DecksRecord> parentPath) {
        super(path, childPath, parentPath, DECKS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class DecksPath extends Decks implements Path<DecksRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DecksPath(Table<O> path, ForeignKey<O, DecksRecord> childPath, InverseForeignKey<O, DecksRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private DecksPath(Name alias, Table<DecksRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public DecksPath as(String alias) {
            return new DecksPath(DSL.name(alias), this);
        }

        @Override
        public DecksPath as(Name alias) {
            return new DecksPath(alias, this);
        }

        @Override
        public DecksPath as(Table<?> alias) {
            return new DecksPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Litdeck.LITDECK;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.DECKS_IDX_DECKS_PUBLIC, Indexes.DECKS_IDX_DECKS_USER_ID);
    }

    @Override
    public Identity<DecksRecord, Integer> getIdentity() {
        return (Identity<DecksRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<DecksRecord> getPrimaryKey() {
        return Keys.KEY_DECKS_PRIMARY;
    }

    @Override
    public List<ForeignKey<DecksRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_DECK_USER);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>litdeck.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.FK_DECK_USER, null);

        return _users;
    }

    private transient DeckProblemsPath _deckProblems;

    /**
     * Get the implicit to-many join path to the
     * <code>litdeck.deck_problems</code> table
     */
    public DeckProblemsPath deckProblems() {
        if (_deckProblems == null)
            _deckProblems = new DeckProblemsPath(this, null, Keys.FK_DECK_PROBLEMS_DECK.getInverseKey());

        return _deckProblems;
    }

    private transient FlashcardReviewsPath _flashcardReviews;

    /**
     * Get the implicit to-many join path to the
     * <code>litdeck.flashcard_reviews</code> table
     */
    public FlashcardReviewsPath flashcardReviews() {
        if (_flashcardReviews == null)
            _flashcardReviews = new FlashcardReviewsPath(this, null, Keys.FK_FLASHCARD_DECK.getInverseKey());

        return _flashcardReviews;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>litdeck.problems</code> table
     */
    public ProblemsPath problems() {
        return deckProblems().problems();
    }

    @Override
    public Decks as(String alias) {
        return new Decks(DSL.name(alias), this);
    }

    @Override
    public Decks as(Name alias) {
        return new Decks(alias, this);
    }

    @Override
    public Decks as(Table<?> alias) {
        return new Decks(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Decks rename(String name) {
        return new Decks(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Decks rename(Name name) {
        return new Decks(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Decks rename(Table<?> name) {
        return new Decks(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Decks where(Condition condition) {
        return new Decks(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Decks where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Decks where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Decks where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Decks where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Decks where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Decks where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Decks where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Decks whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Decks whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
