/*
 * This file is generated by jOOQ.
 */
package com.ib.jooq.tables;


import com.ib.jooq.Indexes;
import com.ib.jooq.Keys;
import com.ib.jooq.Litdeck;
import com.ib.jooq.tables.DeckProblems.DeckProblemsPath;
import com.ib.jooq.tables.Decks.DecksPath;
import com.ib.jooq.tables.FlashcardReviews.FlashcardReviewsPath;
import com.ib.jooq.tables.ProblemsTopic.ProblemsTopicPath;
import com.ib.jooq.tables.ReviewLogs.ReviewLogsPath;
import com.ib.jooq.tables.ReviewSchedules.ReviewSchedulesPath;
import com.ib.jooq.tables.Solutions.SolutionsPath;
import com.ib.jooq.tables.Topics.TopicsPath;
import com.ib.jooq.tables.Users.UsersPath;
import com.ib.jooq.tables.records.ProblemsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSON;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Problems extends TableImpl<ProblemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>litdeck.problems</code>
     */
    public static final Problems PROBLEMS = new Problems();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProblemsRecord> getRecordType() {
        return ProblemsRecord.class;
    }

    /**
     * The column <code>litdeck.problems.id</code>.
     */
    public final TableField<ProblemsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>litdeck.problems.frontend_id</code>.
     */
    public final TableField<ProblemsRecord, Integer> FRONTEND_ID = createField(DSL.name("frontend_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>litdeck.problems.title</code>.
     */
    public final TableField<ProblemsRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>litdeck.problems.title_slug</code>.
     */
    public final TableField<ProblemsRecord, String> TITLE_SLUG = createField(DSL.name("title_slug"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>litdeck.problems.difficulty</code>.
     */
    public final TableField<ProblemsRecord, String> DIFFICULTY = createField(DSL.name("difficulty"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>litdeck.problems.is_paid_only</code>.
     */
    public final TableField<ProblemsRecord, Byte> IS_PAID_ONLY = createField(DSL.name("is_paid_only"), SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>litdeck.problems.content</code>.
     */
    public final TableField<ProblemsRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>litdeck.problems.topic_tags</code>.
     */
    public final TableField<ProblemsRecord, JSON> TOPIC_TAGS = createField(DSL.name("topic_tags"), SQLDataType.JSON, this, "");

    /**
     * The column <code>litdeck.problems.example_testcases</code>.
     */
    public final TableField<ProblemsRecord, String> EXAMPLE_TESTCASES = createField(DSL.name("example_testcases"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>litdeck.problems.similar_questions</code>.
     */
    public final TableField<ProblemsRecord, JSON> SIMILAR_QUESTIONS = createField(DSL.name("similar_questions"), SQLDataType.JSON, this, "");

    /**
     * The column <code>litdeck.problems.created_at</code>.
     */
    public final TableField<ProblemsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private Problems(Name alias, Table<ProblemsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Problems(Name alias, Table<ProblemsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>litdeck.problems</code> table reference
     */
    public Problems(String alias) {
        this(DSL.name(alias), PROBLEMS);
    }

    /**
     * Create an aliased <code>litdeck.problems</code> table reference
     */
    public Problems(Name alias) {
        this(alias, PROBLEMS);
    }

    /**
     * Create a <code>litdeck.problems</code> table reference
     */
    public Problems() {
        this(DSL.name("problems"), null);
    }

    public <O extends Record> Problems(Table<O> path, ForeignKey<O, ProblemsRecord> childPath, InverseForeignKey<O, ProblemsRecord> parentPath) {
        super(path, childPath, parentPath, PROBLEMS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ProblemsPath extends Problems implements Path<ProblemsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ProblemsPath(Table<O> path, ForeignKey<O, ProblemsRecord> childPath, InverseForeignKey<O, ProblemsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ProblemsPath(Name alias, Table<ProblemsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ProblemsPath as(String alias) {
            return new ProblemsPath(DSL.name(alias), this);
        }

        @Override
        public ProblemsPath as(Name alias) {
            return new ProblemsPath(alias, this);
        }

        @Override
        public ProblemsPath as(Table<?> alias) {
            return new ProblemsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Litdeck.LITDECK;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PROBLEMS_IDX_PROBLEMS_DIFFICULTY, Indexes.PROBLEMS_IDX_PROBLEMS_FRONTEND_ID);
    }

    @Override
    public UniqueKey<ProblemsRecord> getPrimaryKey() {
        return Keys.KEY_PROBLEMS_PRIMARY;
    }

    @Override
    public List<UniqueKey<ProblemsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_PROBLEMS_PROBLEMS_TITLE_SLUG_KEY);
    }

    private transient DeckProblemsPath _deckProblems;

    /**
     * Get the implicit to-many join path to the
     * <code>litdeck.deck_problems</code> table
     */
    public DeckProblemsPath deckProblems() {
        if (_deckProblems == null)
            _deckProblems = new DeckProblemsPath(this, null, Keys.FK_DECK_PROBLEMS_PROBLEM.getInverseKey());

        return _deckProblems;
    }

    private transient FlashcardReviewsPath _flashcardReviews;

    /**
     * Get the implicit to-many join path to the
     * <code>litdeck.flashcard_reviews</code> table
     */
    public FlashcardReviewsPath flashcardReviews() {
        if (_flashcardReviews == null)
            _flashcardReviews = new FlashcardReviewsPath(this, null, Keys.FK_FLASHCARD_PROBLEM.getInverseKey());

        return _flashcardReviews;
    }

    private transient ReviewLogsPath _reviewLogs;

    /**
     * Get the implicit to-many join path to the
     * <code>litdeck.review_logs</code> table
     */
    public ReviewLogsPath reviewLogs() {
        if (_reviewLogs == null)
            _reviewLogs = new ReviewLogsPath(this, null, Keys.FK_REVIEW_LOG_PROBLEM.getInverseKey());

        return _reviewLogs;
    }

    private transient ReviewSchedulesPath _reviewSchedules;

    /**
     * Get the implicit to-many join path to the
     * <code>litdeck.review_schedules</code> table
     */
    public ReviewSchedulesPath reviewSchedules() {
        if (_reviewSchedules == null)
            _reviewSchedules = new ReviewSchedulesPath(this, null, Keys.FK_REVIEW_PROBLEM.getInverseKey());

        return _reviewSchedules;
    }

    private transient SolutionsPath _solutions;

    /**
     * Get the implicit to-many join path to the <code>litdeck.solutions</code>
     * table
     */
    public SolutionsPath solutions() {
        if (_solutions == null)
            _solutions = new SolutionsPath(this, null, Keys.FK_SOLUTION_PROBLEM.getInverseKey());

        return _solutions;
    }

    private transient ProblemsTopicPath _problemsTopic;

    /**
     * Get the implicit to-many join path to the
     * <code>litdeck.problems_topic</code> table
     */
    public ProblemsTopicPath problemsTopic() {
        if (_problemsTopic == null)
            _problemsTopic = new ProblemsTopicPath(this, null, Keys.PROBLEMS_TOPIC_IBFK_1.getInverseKey());

        return _problemsTopic;
    }

    /**
     * Get the implicit many-to-many join path to the <code>litdeck.decks</code>
     * table
     */
    public DecksPath decks() {
        return deckProblems().decks();
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>litdeck.topics</code> table
     */
    public TopicsPath topics() {
        return problemsTopic().topics();
    }

    /**
     * Get the implicit many-to-many join path to the <code>litdeck.users</code>
     * table
     */
    public UsersPath users() {
        return reviewSchedules().users();
    }

    @Override
    public Problems as(String alias) {
        return new Problems(DSL.name(alias), this);
    }

    @Override
    public Problems as(Name alias) {
        return new Problems(alias, this);
    }

    @Override
    public Problems as(Table<?> alias) {
        return new Problems(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Problems rename(String name) {
        return new Problems(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Problems rename(Name name) {
        return new Problems(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Problems rename(Table<?> name) {
        return new Problems(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Problems where(Condition condition) {
        return new Problems(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Problems where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Problems where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Problems where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Problems where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Problems where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Problems where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Problems where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Problems whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Problems whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
