/*
 * This file is generated by jOOQ.
 */
package com.ib.jooq.tables;


import com.ib.jooq.Indexes;
import com.ib.jooq.Keys;
import com.ib.jooq.Litdeck;
import com.ib.jooq.tables.Problems.ProblemsPath;
import com.ib.jooq.tables.Topics.TopicsPath;
import com.ib.jooq.tables.records.ProblemsTopicRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProblemsTopic extends TableImpl<ProblemsTopicRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>litdeck.problems_topic</code>
     */
    public static final ProblemsTopic PROBLEMS_TOPIC = new ProblemsTopic();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProblemsTopicRecord> getRecordType() {
        return ProblemsTopicRecord.class;
    }

    /**
     * The column <code>litdeck.problems_topic.problem_id</code>.
     */
    public final TableField<ProblemsTopicRecord, Integer> PROBLEM_ID = createField(DSL.name("problem_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>litdeck.problems_topic.topic_slug</code>.
     */
    public final TableField<ProblemsTopicRecord, String> TOPIC_SLUG = createField(DSL.name("topic_slug"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private ProblemsTopic(Name alias, Table<ProblemsTopicRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ProblemsTopic(Name alias, Table<ProblemsTopicRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>litdeck.problems_topic</code> table reference
     */
    public ProblemsTopic(String alias) {
        this(DSL.name(alias), PROBLEMS_TOPIC);
    }

    /**
     * Create an aliased <code>litdeck.problems_topic</code> table reference
     */
    public ProblemsTopic(Name alias) {
        this(alias, PROBLEMS_TOPIC);
    }

    /**
     * Create a <code>litdeck.problems_topic</code> table reference
     */
    public ProblemsTopic() {
        this(DSL.name("problems_topic"), null);
    }

    public <O extends Record> ProblemsTopic(Table<O> path, ForeignKey<O, ProblemsTopicRecord> childPath, InverseForeignKey<O, ProblemsTopicRecord> parentPath) {
        super(path, childPath, parentPath, PROBLEMS_TOPIC);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ProblemsTopicPath extends ProblemsTopic implements Path<ProblemsTopicRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ProblemsTopicPath(Table<O> path, ForeignKey<O, ProblemsTopicRecord> childPath, InverseForeignKey<O, ProblemsTopicRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ProblemsTopicPath(Name alias, Table<ProblemsTopicRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ProblemsTopicPath as(String alias) {
            return new ProblemsTopicPath(DSL.name(alias), this);
        }

        @Override
        public ProblemsTopicPath as(Name alias) {
            return new ProblemsTopicPath(alias, this);
        }

        @Override
        public ProblemsTopicPath as(Table<?> alias) {
            return new ProblemsTopicPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Litdeck.LITDECK;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PROBLEMS_TOPIC_IDX_PROBLEMS_TOPIC_PROBLEM_ID, Indexes.PROBLEMS_TOPIC_IDX_PROBLEMS_TOPIC_SLUG);
    }

    @Override
    public UniqueKey<ProblemsTopicRecord> getPrimaryKey() {
        return Keys.KEY_PROBLEMS_TOPIC_PRIMARY;
    }

    @Override
    public List<ForeignKey<ProblemsTopicRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PROBLEMS_TOPIC_IBFK_1, Keys.PROBLEMS_TOPIC_IBFK_2);
    }

    private transient ProblemsPath _problems;

    /**
     * Get the implicit join path to the <code>litdeck.problems</code> table.
     */
    public ProblemsPath problems() {
        if (_problems == null)
            _problems = new ProblemsPath(this, Keys.PROBLEMS_TOPIC_IBFK_1, null);

        return _problems;
    }

    private transient TopicsPath _topics;

    /**
     * Get the implicit join path to the <code>litdeck.topics</code> table.
     */
    public TopicsPath topics() {
        if (_topics == null)
            _topics = new TopicsPath(this, Keys.PROBLEMS_TOPIC_IBFK_2, null);

        return _topics;
    }

    @Override
    public ProblemsTopic as(String alias) {
        return new ProblemsTopic(DSL.name(alias), this);
    }

    @Override
    public ProblemsTopic as(Name alias) {
        return new ProblemsTopic(alias, this);
    }

    @Override
    public ProblemsTopic as(Table<?> alias) {
        return new ProblemsTopic(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProblemsTopic rename(String name) {
        return new ProblemsTopic(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProblemsTopic rename(Name name) {
        return new ProblemsTopic(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProblemsTopic rename(Table<?> name) {
        return new ProblemsTopic(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProblemsTopic where(Condition condition) {
        return new ProblemsTopic(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProblemsTopic where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProblemsTopic where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProblemsTopic where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProblemsTopic where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProblemsTopic where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProblemsTopic where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProblemsTopic where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProblemsTopic whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProblemsTopic whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
