/*
 * This file is generated by jOOQ.
 */
package com.ib.jooq.tables;


import com.ib.jooq.Indexes;
import com.ib.jooq.Keys;
import com.ib.jooq.Litdeck;
import com.ib.jooq.tables.Problems.ProblemsPath;
import com.ib.jooq.tables.Users.UsersPath;
import com.ib.jooq.tables.records.ReviewLogsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReviewLogs extends TableImpl<ReviewLogsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>litdeck.review_logs</code>
     */
    public static final ReviewLogs REVIEW_LOGS = new ReviewLogs();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReviewLogsRecord> getRecordType() {
        return ReviewLogsRecord.class;
    }

    /**
     * The column <code>litdeck.review_logs.id</code>.
     */
    public final TableField<ReviewLogsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>litdeck.review_logs.user_id</code>.
     */
    public final TableField<ReviewLogsRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.CHAR(36).nullable(false), this, "");

    /**
     * The column <code>litdeck.review_logs.problem_id</code>.
     */
    public final TableField<ReviewLogsRecord, Integer> PROBLEM_ID = createField(DSL.name("problem_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>litdeck.review_logs.rating</code>.
     */
    public final TableField<ReviewLogsRecord, Integer> RATING = createField(DSL.name("rating"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>litdeck.review_logs.state</code>.
     */
    public final TableField<ReviewLogsRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>litdeck.review_logs.due_date</code>.
     */
    public final TableField<ReviewLogsRecord, LocalDateTime> DUE_DATE = createField(DSL.name("due_date"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>litdeck.review_logs.stability</code>.
     */
    public final TableField<ReviewLogsRecord, Double> STABILITY = createField(DSL.name("stability"), SQLDataType.FLOAT.nullable(false), this, "");

    /**
     * The column <code>litdeck.review_logs.difficulty</code>.
     */
    public final TableField<ReviewLogsRecord, Double> DIFFICULTY = createField(DSL.name("difficulty"), SQLDataType.FLOAT.nullable(false), this, "");

    /**
     * The column <code>litdeck.review_logs.elapsed_days</code>.
     */
    public final TableField<ReviewLogsRecord, Integer> ELAPSED_DAYS = createField(DSL.name("elapsed_days"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>litdeck.review_logs.last_elapsed_days</code>.
     */
    public final TableField<ReviewLogsRecord, Integer> LAST_ELAPSED_DAYS = createField(DSL.name("last_elapsed_days"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>litdeck.review_logs.scheduled_days</code>.
     */
    public final TableField<ReviewLogsRecord, Integer> SCHEDULED_DAYS = createField(DSL.name("scheduled_days"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>litdeck.review_logs.review_date</code>.
     */
    public final TableField<ReviewLogsRecord, LocalDateTime> REVIEW_DATE = createField(DSL.name("review_date"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>litdeck.review_logs.created_at</code>.
     */
    public final TableField<ReviewLogsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private ReviewLogs(Name alias, Table<ReviewLogsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ReviewLogs(Name alias, Table<ReviewLogsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>litdeck.review_logs</code> table reference
     */
    public ReviewLogs(String alias) {
        this(DSL.name(alias), REVIEW_LOGS);
    }

    /**
     * Create an aliased <code>litdeck.review_logs</code> table reference
     */
    public ReviewLogs(Name alias) {
        this(alias, REVIEW_LOGS);
    }

    /**
     * Create a <code>litdeck.review_logs</code> table reference
     */
    public ReviewLogs() {
        this(DSL.name("review_logs"), null);
    }

    public <O extends Record> ReviewLogs(Table<O> path, ForeignKey<O, ReviewLogsRecord> childPath, InverseForeignKey<O, ReviewLogsRecord> parentPath) {
        super(path, childPath, parentPath, REVIEW_LOGS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReviewLogsPath extends ReviewLogs implements Path<ReviewLogsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ReviewLogsPath(Table<O> path, ForeignKey<O, ReviewLogsRecord> childPath, InverseForeignKey<O, ReviewLogsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReviewLogsPath(Name alias, Table<ReviewLogsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReviewLogsPath as(String alias) {
            return new ReviewLogsPath(DSL.name(alias), this);
        }

        @Override
        public ReviewLogsPath as(Name alias) {
            return new ReviewLogsPath(alias, this);
        }

        @Override
        public ReviewLogsPath as(Table<?> alias) {
            return new ReviewLogsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Litdeck.LITDECK;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.REVIEW_LOGS_IDX_REVIEW_LOGS_PROBLEM_ID, Indexes.REVIEW_LOGS_IDX_REVIEW_LOGS_REVIEW_DATE, Indexes.REVIEW_LOGS_IDX_REVIEW_LOGS_USER_ID);
    }

    @Override
    public Identity<ReviewLogsRecord, Integer> getIdentity() {
        return (Identity<ReviewLogsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReviewLogsRecord> getPrimaryKey() {
        return Keys.KEY_REVIEW_LOGS_PRIMARY;
    }

    @Override
    public List<ForeignKey<ReviewLogsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_REVIEW_LOG_PROBLEM, Keys.FK_REVIEW_LOG_USER);
    }

    private transient ProblemsPath _problems;

    /**
     * Get the implicit join path to the <code>litdeck.problems</code> table.
     */
    public ProblemsPath problems() {
        if (_problems == null)
            _problems = new ProblemsPath(this, Keys.FK_REVIEW_LOG_PROBLEM, null);

        return _problems;
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>litdeck.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.FK_REVIEW_LOG_USER, null);

        return _users;
    }

    @Override
    public ReviewLogs as(String alias) {
        return new ReviewLogs(DSL.name(alias), this);
    }

    @Override
    public ReviewLogs as(Name alias) {
        return new ReviewLogs(alias, this);
    }

    @Override
    public ReviewLogs as(Table<?> alias) {
        return new ReviewLogs(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReviewLogs rename(String name) {
        return new ReviewLogs(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReviewLogs rename(Name name) {
        return new ReviewLogs(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReviewLogs rename(Table<?> name) {
        return new ReviewLogs(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReviewLogs where(Condition condition) {
        return new ReviewLogs(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReviewLogs where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReviewLogs where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReviewLogs where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReviewLogs where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReviewLogs where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReviewLogs where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReviewLogs where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReviewLogs whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReviewLogs whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
