/*
 * This file is generated by jOOQ.
 */
package com.ib.jooq.tables;


import com.ib.jooq.Indexes;
import com.ib.jooq.Keys;
import com.ib.jooq.Litdeck;
import com.ib.jooq.tables.Users.UsersPath;
import com.ib.jooq.tables.records.SubmissionsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Submissions extends TableImpl<SubmissionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>litdeck.submissions</code>
     */
    public static final Submissions SUBMISSIONS = new Submissions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SubmissionsRecord> getRecordType() {
        return SubmissionsRecord.class;
    }

    /**
     * The column <code>litdeck.submissions.id</code>.
     */
    public final TableField<SubmissionsRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>litdeck.submissions.title</code>.
     */
    public final TableField<SubmissionsRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>litdeck.submissions.title_slug</code>.
     */
    public final TableField<SubmissionsRecord, String> TITLE_SLUG = createField(DSL.name("title_slug"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>litdeck.submissions.submitted_at</code>.
     */
    public final TableField<SubmissionsRecord, LocalDateTime> SUBMITTED_AT = createField(DSL.name("submitted_at"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>litdeck.submissions.created_at</code>.
     */
    public final TableField<SubmissionsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>litdeck.submissions.user_id</code>.
     */
    public final TableField<SubmissionsRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.CHAR(36).nullable(false), this, "");

    private Submissions(Name alias, Table<SubmissionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Submissions(Name alias, Table<SubmissionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>litdeck.submissions</code> table reference
     */
    public Submissions(String alias) {
        this(DSL.name(alias), SUBMISSIONS);
    }

    /**
     * Create an aliased <code>litdeck.submissions</code> table reference
     */
    public Submissions(Name alias) {
        this(alias, SUBMISSIONS);
    }

    /**
     * Create a <code>litdeck.submissions</code> table reference
     */
    public Submissions() {
        this(DSL.name("submissions"), null);
    }

    public <O extends Record> Submissions(Table<O> path, ForeignKey<O, SubmissionsRecord> childPath, InverseForeignKey<O, SubmissionsRecord> parentPath) {
        super(path, childPath, parentPath, SUBMISSIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SubmissionsPath extends Submissions implements Path<SubmissionsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SubmissionsPath(Table<O> path, ForeignKey<O, SubmissionsRecord> childPath, InverseForeignKey<O, SubmissionsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SubmissionsPath(Name alias, Table<SubmissionsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SubmissionsPath as(String alias) {
            return new SubmissionsPath(DSL.name(alias), this);
        }

        @Override
        public SubmissionsPath as(Name alias) {
            return new SubmissionsPath(alias, this);
        }

        @Override
        public SubmissionsPath as(Table<?> alias) {
            return new SubmissionsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Litdeck.LITDECK;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SUBMISSIONS_IDX_SUBMISSIONS_USER_TIME);
    }

    @Override
    public UniqueKey<SubmissionsRecord> getPrimaryKey() {
        return Keys.KEY_SUBMISSIONS_PRIMARY;
    }

    @Override
    public List<ForeignKey<SubmissionsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_USER);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>litdeck.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.FK_USER, null);

        return _users;
    }

    @Override
    public Submissions as(String alias) {
        return new Submissions(DSL.name(alias), this);
    }

    @Override
    public Submissions as(Name alias) {
        return new Submissions(alias, this);
    }

    @Override
    public Submissions as(Table<?> alias) {
        return new Submissions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Submissions rename(String name) {
        return new Submissions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Submissions rename(Name name) {
        return new Submissions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Submissions rename(Table<?> name) {
        return new Submissions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Submissions where(Condition condition) {
        return new Submissions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Submissions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Submissions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Submissions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Submissions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Submissions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Submissions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Submissions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Submissions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Submissions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
