/*
 * This file is generated by jOOQ.
 */
package com.ls.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserDsa implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String userId;
    private String title;
    private String titleSlug;
    private String difficulty;
    private Integer isPaidOnly;
    private String description;
    private String solution;
    private String note;
    private String exampleTestcases;
    private LocalDateTime createdDate;
    private LocalDateTime lastUpdatedDate;

    public UserDsa() {}

    public UserDsa(UserDsa value) {
        this.id = value.id;
        this.userId = value.userId;
        this.title = value.title;
        this.titleSlug = value.titleSlug;
        this.difficulty = value.difficulty;
        this.isPaidOnly = value.isPaidOnly;
        this.description = value.description;
        this.solution = value.solution;
        this.note = value.note;
        this.exampleTestcases = value.exampleTestcases;
        this.createdDate = value.createdDate;
        this.lastUpdatedDate = value.lastUpdatedDate;
    }

    public UserDsa(
        Integer id,
        String userId,
        String title,
        String titleSlug,
        String difficulty,
        Integer isPaidOnly,
        String description,
        String solution,
        String note,
        String exampleTestcases,
        LocalDateTime createdDate,
        LocalDateTime lastUpdatedDate
    ) {
        this.id = id;
        this.userId = userId;
        this.title = title;
        this.titleSlug = titleSlug;
        this.difficulty = difficulty;
        this.isPaidOnly = isPaidOnly;
        this.description = description;
        this.solution = solution;
        this.note = note;
        this.exampleTestcases = exampleTestcases;
        this.createdDate = createdDate;
        this.lastUpdatedDate = lastUpdatedDate;
    }

    /**
     * Getter for <code>user_dsa.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>user_dsa.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>user_dsa.user_id</code>.
     */
    public String getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>user_dsa.user_id</code>.
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>user_dsa.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>user_dsa.title</code>.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>user_dsa.title_slug</code>.
     */
    public String getTitleSlug() {
        return this.titleSlug;
    }

    /**
     * Setter for <code>user_dsa.title_slug</code>.
     */
    public void setTitleSlug(String titleSlug) {
        this.titleSlug = titleSlug;
    }

    /**
     * Getter for <code>user_dsa.difficulty</code>.
     */
    public String getDifficulty() {
        return this.difficulty;
    }

    /**
     * Setter for <code>user_dsa.difficulty</code>.
     */
    public void setDifficulty(String difficulty) {
        this.difficulty = difficulty;
    }

    /**
     * Getter for <code>user_dsa.is_paid_only</code>.
     */
    public Integer getIsPaidOnly() {
        return this.isPaidOnly;
    }

    /**
     * Setter for <code>user_dsa.is_paid_only</code>.
     */
    public void setIsPaidOnly(Integer isPaidOnly) {
        this.isPaidOnly = isPaidOnly;
    }

    /**
     * Getter for <code>user_dsa.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>user_dsa.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>user_dsa.solution</code>.
     */
    public String getSolution() {
        return this.solution;
    }

    /**
     * Setter for <code>user_dsa.solution</code>.
     */
    public void setSolution(String solution) {
        this.solution = solution;
    }

    /**
     * Getter for <code>user_dsa.note</code>.
     */
    public String getNote() {
        return this.note;
    }

    /**
     * Setter for <code>user_dsa.note</code>.
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * Getter for <code>user_dsa.example_testcases</code>.
     */
    public String getExampleTestcases() {
        return this.exampleTestcases;
    }

    /**
     * Setter for <code>user_dsa.example_testcases</code>.
     */
    public void setExampleTestcases(String exampleTestcases) {
        this.exampleTestcases = exampleTestcases;
    }

    /**
     * Getter for <code>user_dsa.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>user_dsa.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>user_dsa.last_updated_date</code>.
     */
    public LocalDateTime getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }

    /**
     * Setter for <code>user_dsa.last_updated_date</code>.
     */
    public void setLastUpdatedDate(LocalDateTime lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserDsa other = (UserDsa) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.titleSlug == null) {
            if (other.titleSlug != null)
                return false;
        }
        else if (!this.titleSlug.equals(other.titleSlug))
            return false;
        if (this.difficulty == null) {
            if (other.difficulty != null)
                return false;
        }
        else if (!this.difficulty.equals(other.difficulty))
            return false;
        if (this.isPaidOnly == null) {
            if (other.isPaidOnly != null)
                return false;
        }
        else if (!this.isPaidOnly.equals(other.isPaidOnly))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.solution == null) {
            if (other.solution != null)
                return false;
        }
        else if (!this.solution.equals(other.solution))
            return false;
        if (this.note == null) {
            if (other.note != null)
                return false;
        }
        else if (!this.note.equals(other.note))
            return false;
        if (this.exampleTestcases == null) {
            if (other.exampleTestcases != null)
                return false;
        }
        else if (!this.exampleTestcases.equals(other.exampleTestcases))
            return false;
        if (this.createdDate == null) {
            if (other.createdDate != null)
                return false;
        }
        else if (!this.createdDate.equals(other.createdDate))
            return false;
        if (this.lastUpdatedDate == null) {
            if (other.lastUpdatedDate != null)
                return false;
        }
        else if (!this.lastUpdatedDate.equals(other.lastUpdatedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.titleSlug == null) ? 0 : this.titleSlug.hashCode());
        result = prime * result + ((this.difficulty == null) ? 0 : this.difficulty.hashCode());
        result = prime * result + ((this.isPaidOnly == null) ? 0 : this.isPaidOnly.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.solution == null) ? 0 : this.solution.hashCode());
        result = prime * result + ((this.note == null) ? 0 : this.note.hashCode());
        result = prime * result + ((this.exampleTestcases == null) ? 0 : this.exampleTestcases.hashCode());
        result = prime * result + ((this.createdDate == null) ? 0 : this.createdDate.hashCode());
        result = prime * result + ((this.lastUpdatedDate == null) ? 0 : this.lastUpdatedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserDsa (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(title);
        sb.append(", ").append(titleSlug);
        sb.append(", ").append(difficulty);
        sb.append(", ").append(isPaidOnly);
        sb.append(", ").append(description);
        sb.append(", ").append(solution);
        sb.append(", ").append(note);
        sb.append(", ").append(exampleTestcases);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(lastUpdatedDate);

        sb.append(")");
        return sb.toString();
    }
}
