/*
 * This file is generated by jOOQ.
 */
package com.ls.jooq.tables.pojos;


import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Userspojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String email;
    private String firstName;
    private String lastName;
    private LocalDateTime createdDate;
    private LocalDateTime lastUpdatedDate;
    private String leetstackUsername;

    public Userspojo() {}

    public Userspojo(Userspojo value) {
        this.id = value.id;
        this.email = value.email;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.createdDate = value.createdDate;
        this.lastUpdatedDate = value.lastUpdatedDate;
        this.leetstackUsername = value.leetstackUsername;
    }

    public Userspojo(
        String id,
        String email,
        String firstName,
        String lastName,
        LocalDateTime createdDate,
        LocalDateTime lastUpdatedDate,
        String leetstackUsername
    ) {
        this.id = id;
        this.email = email;
        this.firstName = firstName;
        this.lastName = lastName;
        this.createdDate = createdDate;
        this.lastUpdatedDate = lastUpdatedDate;
        this.leetstackUsername = leetstackUsername;
    }

    /**
     * Getter for <code>leetstack.users.id</code>.
     */
    @Size(max = 36)
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>leetstack.users.id</code>.
     */
    public Userspojo setId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>leetstack.users.email</code>.
     */
    @Size(max = 255)
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>leetstack.users.email</code>.
     */
    public Userspojo setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>leetstack.users.first_name</code>.
     */
    @Size(max = 100)
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Setter for <code>leetstack.users.first_name</code>.
     */
    public Userspojo setFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    /**
     * Getter for <code>leetstack.users.last_name</code>.
     */
    @Size(max = 100)
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Setter for <code>leetstack.users.last_name</code>.
     */
    public Userspojo setLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }

    /**
     * Getter for <code>leetstack.users.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>leetstack.users.created_date</code>.
     */
    public Userspojo setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    /**
     * Getter for <code>leetstack.users.last_updated_date</code>.
     */
    public LocalDateTime getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }

    /**
     * Setter for <code>leetstack.users.last_updated_date</code>.
     */
    public Userspojo setLastUpdatedDate(LocalDateTime lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
        return this;
    }

    /**
     * Getter for <code>leetstack.users.leetstack_username</code>.
     */
    @Size(max = 255)
    public String getLeetstackUsername() {
        return this.leetstackUsername;
    }

    /**
     * Setter for <code>leetstack.users.leetstack_username</code>.
     */
    public Userspojo setLeetstackUsername(String leetstackUsername) {
        this.leetstackUsername = leetstackUsername;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Userspojo other = (Userspojo) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.firstName == null) {
            if (other.firstName != null)
                return false;
        }
        else if (!this.firstName.equals(other.firstName))
            return false;
        if (this.lastName == null) {
            if (other.lastName != null)
                return false;
        }
        else if (!this.lastName.equals(other.lastName))
            return false;
        if (this.createdDate == null) {
            if (other.createdDate != null)
                return false;
        }
        else if (!this.createdDate.equals(other.createdDate))
            return false;
        if (this.lastUpdatedDate == null) {
            if (other.lastUpdatedDate != null)
                return false;
        }
        else if (!this.lastUpdatedDate.equals(other.lastUpdatedDate))
            return false;
        if (this.leetstackUsername == null) {
            if (other.leetstackUsername != null)
                return false;
        }
        else if (!this.leetstackUsername.equals(other.leetstackUsername))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.firstName == null) ? 0 : this.firstName.hashCode());
        result = prime * result + ((this.lastName == null) ? 0 : this.lastName.hashCode());
        result = prime * result + ((this.createdDate == null) ? 0 : this.createdDate.hashCode());
        result = prime * result + ((this.lastUpdatedDate == null) ? 0 : this.lastUpdatedDate.hashCode());
        result = prime * result + ((this.leetstackUsername == null) ? 0 : this.leetstackUsername.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Userspojo (");

        sb.append(id);
        sb.append(", ").append(email);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(lastUpdatedDate);
        sb.append(", ").append(leetstackUsername);

        sb.append(")");
        return sb.toString();
    }
}
