/*
 * This file is generated by jOOQ.
 */
package com.ls.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserApiKey implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String userId;
    private String keyHash;
    private String label;
    private Byte revoked;
    private LocalDateTime createdDate;
    private LocalDateTime lastUsedDate;

    public UserApiKey() {}

    public UserApiKey(UserApiKey value) {
        this.id = value.id;
        this.userId = value.userId;
        this.keyHash = value.keyHash;
        this.label = value.label;
        this.revoked = value.revoked;
        this.createdDate = value.createdDate;
        this.lastUsedDate = value.lastUsedDate;
    }

    public UserApiKey(
        Long id,
        String userId,
        String keyHash,
        String label,
        Byte revoked,
        LocalDateTime createdDate,
        LocalDateTime lastUsedDate
    ) {
        this.id = id;
        this.userId = userId;
        this.keyHash = keyHash;
        this.label = label;
        this.revoked = revoked;
        this.createdDate = createdDate;
        this.lastUsedDate = lastUsedDate;
    }

    /**
     * Getter for <code>leetstack.user_api_key.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>leetstack.user_api_key.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>leetstack.user_api_key.user_id</code>.
     */
    public String getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>leetstack.user_api_key.user_id</code>.
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>leetstack.user_api_key.key_hash</code>.
     */
    public String getKeyHash() {
        return this.keyHash;
    }

    /**
     * Setter for <code>leetstack.user_api_key.key_hash</code>.
     */
    public void setKeyHash(String keyHash) {
        this.keyHash = keyHash;
    }

    /**
     * Getter for <code>leetstack.user_api_key.label</code>.
     */
    public String getLabel() {
        return this.label;
    }

    /**
     * Setter for <code>leetstack.user_api_key.label</code>.
     */
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * Getter for <code>leetstack.user_api_key.revoked</code>.
     */
    public Byte getRevoked() {
        return this.revoked;
    }

    /**
     * Setter for <code>leetstack.user_api_key.revoked</code>.
     */
    public void setRevoked(Byte revoked) {
        this.revoked = revoked;
    }

    /**
     * Getter for <code>leetstack.user_api_key.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>leetstack.user_api_key.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>leetstack.user_api_key.last_used_date</code>.
     */
    public LocalDateTime getLastUsedDate() {
        return this.lastUsedDate;
    }

    /**
     * Setter for <code>leetstack.user_api_key.last_used_date</code>.
     */
    public void setLastUsedDate(LocalDateTime lastUsedDate) {
        this.lastUsedDate = lastUsedDate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserApiKey other = (UserApiKey) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.keyHash == null) {
            if (other.keyHash != null)
                return false;
        }
        else if (!this.keyHash.equals(other.keyHash))
            return false;
        if (this.label == null) {
            if (other.label != null)
                return false;
        }
        else if (!this.label.equals(other.label))
            return false;
        if (this.revoked == null) {
            if (other.revoked != null)
                return false;
        }
        else if (!this.revoked.equals(other.revoked))
            return false;
        if (this.createdDate == null) {
            if (other.createdDate != null)
                return false;
        }
        else if (!this.createdDate.equals(other.createdDate))
            return false;
        if (this.lastUsedDate == null) {
            if (other.lastUsedDate != null)
                return false;
        }
        else if (!this.lastUsedDate.equals(other.lastUsedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.keyHash == null) ? 0 : this.keyHash.hashCode());
        result = prime * result + ((this.label == null) ? 0 : this.label.hashCode());
        result = prime * result + ((this.revoked == null) ? 0 : this.revoked.hashCode());
        result = prime * result + ((this.createdDate == null) ? 0 : this.createdDate.hashCode());
        result = prime * result + ((this.lastUsedDate == null) ? 0 : this.lastUsedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserApiKey (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(keyHash);
        sb.append(", ").append(label);
        sb.append(", ").append(revoked);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(lastUsedDate);

        sb.append(")");
        return sb.toString();
    }
}
