/*
 * This file is generated by jOOQ.
 */
package com.ls.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class User implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String email;
    private String firstName;
    private String lastName;
    private LocalDateTime createdDate;
    private LocalDateTime lastUpdatedDate;
    private String leetstackUsername;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.email = value.email;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.createdDate = value.createdDate;
        this.lastUpdatedDate = value.lastUpdatedDate;
        this.leetstackUsername = value.leetstackUsername;
    }

    public User(
        String id,
        String email,
        String firstName,
        String lastName,
        LocalDateTime createdDate,
        LocalDateTime lastUpdatedDate,
        String leetstackUsername
    ) {
        this.id = id;
        this.email = email;
        this.firstName = firstName;
        this.lastName = lastName;
        this.createdDate = createdDate;
        this.lastUpdatedDate = lastUpdatedDate;
        this.leetstackUsername = leetstackUsername;
    }

    /**
     * Getter for <code>user.id</code>.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>user.id</code>.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for <code>user.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>user.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>user.first_name</code>.
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Setter for <code>user.first_name</code>.
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Getter for <code>user.last_name</code>.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Setter for <code>user.last_name</code>.
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Getter for <code>user.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>user.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>user.last_updated_date</code>.
     */
    public LocalDateTime getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }

    /**
     * Setter for <code>user.last_updated_date</code>.
     */
    public void setLastUpdatedDate(LocalDateTime lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    /**
     * Getter for <code>user.leetstack_username</code>.
     */
    public String getLeetstackUsername() {
        return this.leetstackUsername;
    }

    /**
     * Setter for <code>user.leetstack_username</code>.
     */
    public void setLeetstackUsername(String leetstackUsername) {
        this.leetstackUsername = leetstackUsername;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final User other = (User) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.firstName == null) {
            if (other.firstName != null)
                return false;
        }
        else if (!this.firstName.equals(other.firstName))
            return false;
        if (this.lastName == null) {
            if (other.lastName != null)
                return false;
        }
        else if (!this.lastName.equals(other.lastName))
            return false;
        if (this.createdDate == null) {
            if (other.createdDate != null)
                return false;
        }
        else if (!this.createdDate.equals(other.createdDate))
            return false;
        if (this.lastUpdatedDate == null) {
            if (other.lastUpdatedDate != null)
                return false;
        }
        else if (!this.lastUpdatedDate.equals(other.lastUpdatedDate))
            return false;
        if (this.leetstackUsername == null) {
            if (other.leetstackUsername != null)
                return false;
        }
        else if (!this.leetstackUsername.equals(other.leetstackUsername))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.firstName == null) ? 0 : this.firstName.hashCode());
        result = prime * result + ((this.lastName == null) ? 0 : this.lastName.hashCode());
        result = prime * result + ((this.createdDate == null) ? 0 : this.createdDate.hashCode());
        result = prime * result + ((this.lastUpdatedDate == null) ? 0 : this.lastUpdatedDate.hashCode());
        result = prime * result + ((this.leetstackUsername == null) ? 0 : this.leetstackUsername.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(email);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(lastUpdatedDate);
        sb.append(", ").append(leetstackUsername);

        sb.append(")");
        return sb.toString();
    }
}
