/*
 * This file is generated by jOOQ.
 */
package com.ls.jooq;


import com.ls.jooq.tables.User;
import com.ls.jooq.tables.UserApiKey;
import com.ls.jooq.tables.UserDsa;
import com.ls.jooq.tables.records.UserApiKeyRecord;
import com.ls.jooq.tables.records.UserDsaRecord;
import com.ls.jooq.tables.records.UserRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * leetstack.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, DSL.name("KEY_user_PRIMARY"), new TableField[] { User.USER.ID }, true);
    public static final UniqueKey<UserRecord> KEY_USER_UQ_USER_LEETSTACK_USERNAME = Internal.createUniqueKey(User.USER, DSL.name("KEY_user_uq_user_leetstack_username"), new TableField[] { User.USER.LEETSTACK_USERNAME }, true);
    public static final UniqueKey<UserApiKeyRecord> KEY_USER_API_KEY_PRIMARY = Internal.createUniqueKey(UserApiKey.USER_API_KEY, DSL.name("KEY_user_api_key_PRIMARY"), new TableField[] { UserApiKey.USER_API_KEY.ID }, true);
    public static final UniqueKey<UserApiKeyRecord> KEY_USER_API_KEY_UQ_USER_API_KEY_HASH = Internal.createUniqueKey(UserApiKey.USER_API_KEY, DSL.name("KEY_user_api_key_uq_user_api_key_hash"), new TableField[] { UserApiKey.USER_API_KEY.KEY_HASH }, true);
    public static final UniqueKey<UserDsaRecord> KEY_USER_DSA_PRIMARY = Internal.createUniqueKey(UserDsa.USER_DSA, DSL.name("KEY_user_dsa_PRIMARY"), new TableField[] { UserDsa.USER_DSA.ID }, true);
    public static final UniqueKey<UserDsaRecord> KEY_USER_DSA_UQ_USER_DSA_USER_SLUG = Internal.createUniqueKey(UserDsa.USER_DSA, DSL.name("KEY_user_dsa_uq_user_dsa_user_slug"), new TableField[] { UserDsa.USER_DSA.USER_ID, UserDsa.USER_DSA.TITLE_SLUG }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<UserApiKeyRecord, UserRecord> USER_API_KEY_IBFK_1 = Internal.createForeignKey(UserApiKey.USER_API_KEY, DSL.name("user_api_key_ibfk_1"), new TableField[] { UserApiKey.USER_API_KEY.USER_ID }, Keys.KEY_USER_PRIMARY, new TableField[] { User.USER.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<UserDsaRecord, UserRecord> FK_USER_DSA_USER = Internal.createForeignKey(UserDsa.USER_DSA, DSL.name("fk_user_dsa_user"), new TableField[] { UserDsa.USER_DSA.USER_ID }, Keys.KEY_USER_PRIMARY, new TableField[] { User.USER.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
}
