/*
 * This file is generated by jOOQ.
 */
package com.ls.jooq;


import com.ls.jooq.tables.UserDsa;
import com.ls.jooq.tables.Users;
import com.ls.jooq.tables.records.UserDsaRecord;
import com.ls.jooq.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * leetstack.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<UserDsaRecord> KEY_USER_DSA_PRIMARY = Internal.createUniqueKey(UserDsa.USER_DSA, DSL.name("KEY_user_dsa_PRIMARY"), new TableField[] { UserDsa.USER_DSA.ID }, true);
    public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = Internal.createUniqueKey(Users.USERS, DSL.name("KEY_users_PRIMARY"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<UsersRecord> KEY_USERS_UNIQUE_USERNAME = Internal.createUniqueKey(Users.USERS, DSL.name("KEY_users_unique_username"), new TableField[] { Users.USERS.LEETSTACK_USERNAME }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<UserDsaRecord, UsersRecord> FK_USER_DSA_USER_ID = Internal.createForeignKey(UserDsa.USER_DSA, DSL.name("fk_user_dsa_user_id"), new TableField[] { UserDsa.USER_DSA.USER_ID }, Keys.KEY_USERS_PRIMARY, new TableField[] { Users.USERS.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
}
