/*
 * This file is generated by jOOQ.
 */
package com.ls.jooq;


import com.ls.jooq.tables.UserDsa;
import com.ls.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Leetstack extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>leetstack</code>
     */
    public static final Leetstack LEETSTACK = new Leetstack();

    /**
     * The table <code>leetstack.user_dsa</code>.
     */
    public final UserDsa USER_DSA = UserDsa.USER_DSA;

    /**
     * The table <code>leetstack.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Leetstack() {
        super(DSL.name("leetstack"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            UserDsa.USER_DSA,
            Users.USERS
        );
    }
}
