/*
 * This file is generated by jOOQ.
 */
package com.ls.jooq;


import com.ls.jooq.tables.User;
import com.ls.jooq.tables.UserApiKey;
import com.ls.jooq.tables.UserDsa;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Leetstack extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>leetstack</code>
     */
    public static final Leetstack LEETSTACK = new Leetstack();

    /**
     * The table <code>leetstack.user</code>.
     */
    public final User USER = User.USER;

    /**
     * The table <code>leetstack.user_api_key</code>.
     */
    public final UserApiKey USER_API_KEY = UserApiKey.USER_API_KEY;

    /**
     * The table <code>leetstack.user_dsa</code>.
     */
    public final UserDsa USER_DSA = UserDsa.USER_DSA;

    /**
     * No further instances allowed
     */
    private Leetstack() {
        super(DSL.name("leetstack"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            User.USER,
            UserApiKey.USER_API_KEY,
            UserDsa.USER_DSA
        );
    }
}
