/*
 * This file is generated by jOOQ.
 */
package com.ls.jooq;


import com.ls.jooq.tables.UserDsa;
import com.ls.jooq.tables.Users;


/**
 * Convenience access to all tables in leetstack.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>leetstack.user_dsa</code>.
     */
    public static final UserDsa USER_DSA = UserDsa.USER_DSA;

    /**
     * The table <code>leetstack.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
