/*
 * This file is generated by jOOQ.
 */
package com.ls.jooq;


import com.ls.jooq.tables.Databasechangelog;
import com.ls.jooq.tables.Databasechangeloglock;
import com.ls.jooq.tables.User;
import com.ls.jooq.tables.UserApiKey;
import com.ls.jooq.tables.UserDsa;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>DATABASECHANGELOG</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>DATABASECHANGELOGLOCK</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>user_api_key</code>.
     */
    public static final UserApiKey USER_API_KEY = UserApiKey.USER_API_KEY;

    /**
     * The table <code>user_dsa</code>.
     */
    public static final UserDsa USER_DSA = UserDsa.USER_DSA;
}
