/*
 * This file is generated by jOOQ.
 */
package com.litdeck.backend.jooq;


import com.litdeck.backend.jooq.tables.DeckProblems;
import com.litdeck.backend.jooq.tables.Decks;
import com.litdeck.backend.jooq.tables.FlashcardReviews;
import com.litdeck.backend.jooq.tables.Problems;
import com.litdeck.backend.jooq.tables.ProblemsTopic;
import com.litdeck.backend.jooq.tables.ReviewLogs;
import com.litdeck.backend.jooq.tables.ReviewSchedules;
import com.litdeck.backend.jooq.tables.Solutions;
import com.litdeck.backend.jooq.tables.Submissions;
import com.litdeck.backend.jooq.tables.Topics;
import com.litdeck.backend.jooq.tables.Users;
import com.litdeck.backend.jooq.tables.records.DeckProblemsRecord;
import com.litdeck.backend.jooq.tables.records.DecksRecord;
import com.litdeck.backend.jooq.tables.records.FlashcardReviewsRecord;
import com.litdeck.backend.jooq.tables.records.ProblemsRecord;
import com.litdeck.backend.jooq.tables.records.ProblemsTopicRecord;
import com.litdeck.backend.jooq.tables.records.ReviewLogsRecord;
import com.litdeck.backend.jooq.tables.records.ReviewSchedulesRecord;
import com.litdeck.backend.jooq.tables.records.SolutionsRecord;
import com.litdeck.backend.jooq.tables.records.SubmissionsRecord;
import com.litdeck.backend.jooq.tables.records.TopicsRecord;
import com.litdeck.backend.jooq.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * litdeck.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DeckProblemsRecord> KEY_DECK_PROBLEMS_PRIMARY = Internal.createUniqueKey(DeckProblems.DECK_PROBLEMS, DSL.name("KEY_deck_problems_PRIMARY"), new TableField[] { DeckProblems.DECK_PROBLEMS.DECK_ID, DeckProblems.DECK_PROBLEMS.PROBLEM_ID }, true);
    public static final UniqueKey<DecksRecord> KEY_DECKS_PRIMARY = Internal.createUniqueKey(Decks.DECKS, DSL.name("KEY_decks_PRIMARY"), new TableField[] { Decks.DECKS.ID }, true);
    public static final UniqueKey<FlashcardReviewsRecord> KEY_FLASHCARD_REVIEWS_PRIMARY = Internal.createUniqueKey(FlashcardReviews.FLASHCARD_REVIEWS, DSL.name("KEY_flashcard_reviews_PRIMARY"), new TableField[] { FlashcardReviews.FLASHCARD_REVIEWS.ID }, true);
    public static final UniqueKey<FlashcardReviewsRecord> KEY_FLASHCARD_REVIEWS_UNIQUE_USER_DECK_PROBLEM = Internal.createUniqueKey(FlashcardReviews.FLASHCARD_REVIEWS, DSL.name("KEY_flashcard_reviews_unique_user_deck_problem"), new TableField[] { FlashcardReviews.FLASHCARD_REVIEWS.USER_ID, FlashcardReviews.FLASHCARD_REVIEWS.DECK_ID, FlashcardReviews.FLASHCARD_REVIEWS.PROBLEM_ID }, true);
    public static final UniqueKey<ProblemsRecord> KEY_PROBLEMS_PRIMARY = Internal.createUniqueKey(Problems.PROBLEMS, DSL.name("KEY_problems_PRIMARY"), new TableField[] { Problems.PROBLEMS.ID }, true);
    public static final UniqueKey<ProblemsRecord> KEY_PROBLEMS_PROBLEMS_TITLE_SLUG_KEY = Internal.createUniqueKey(Problems.PROBLEMS, DSL.name("KEY_problems_problems_title_slug_key"), new TableField[] { Problems.PROBLEMS.TITLE_SLUG }, true);
    public static final UniqueKey<ProblemsTopicRecord> KEY_PROBLEMS_TOPIC_PRIMARY = Internal.createUniqueKey(ProblemsTopic.PROBLEMS_TOPIC, DSL.name("KEY_problems_topic_PRIMARY"), new TableField[] { ProblemsTopic.PROBLEMS_TOPIC.PROBLEM_ID, ProblemsTopic.PROBLEMS_TOPIC.TOPIC_SLUG }, true);
    public static final UniqueKey<ReviewLogsRecord> KEY_REVIEW_LOGS_PRIMARY = Internal.createUniqueKey(ReviewLogs.REVIEW_LOGS, DSL.name("KEY_review_logs_PRIMARY"), new TableField[] { ReviewLogs.REVIEW_LOGS.ID }, true);
    public static final UniqueKey<ReviewSchedulesRecord> KEY_REVIEW_SCHEDULES_PRIMARY = Internal.createUniqueKey(ReviewSchedules.REVIEW_SCHEDULES, DSL.name("KEY_review_schedules_PRIMARY"), new TableField[] { ReviewSchedules.REVIEW_SCHEDULES.ID }, true);
    public static final UniqueKey<ReviewSchedulesRecord> KEY_REVIEW_SCHEDULES_UNIQUE_USER_PROBLEM = Internal.createUniqueKey(ReviewSchedules.REVIEW_SCHEDULES, DSL.name("KEY_review_schedules_unique_user_problem"), new TableField[] { ReviewSchedules.REVIEW_SCHEDULES.USER_ID, ReviewSchedules.REVIEW_SCHEDULES.PROBLEM_ID }, true);
    public static final UniqueKey<SolutionsRecord> KEY_SOLUTIONS_PRIMARY = Internal.createUniqueKey(Solutions.SOLUTIONS, DSL.name("KEY_solutions_PRIMARY"), new TableField[] { Solutions.SOLUTIONS.ID }, true);
    public static final UniqueKey<SubmissionsRecord> KEY_SUBMISSIONS_PRIMARY = Internal.createUniqueKey(Submissions.SUBMISSIONS, DSL.name("KEY_submissions_PRIMARY"), new TableField[] { Submissions.SUBMISSIONS.ID }, true);
    public static final UniqueKey<TopicsRecord> KEY_TOPICS_NAME = Internal.createUniqueKey(Topics.TOPICS, DSL.name("KEY_topics_name"), new TableField[] { Topics.TOPICS.NAME }, true);
    public static final UniqueKey<TopicsRecord> KEY_TOPICS_PRIMARY = Internal.createUniqueKey(Topics.TOPICS, DSL.name("KEY_topics_PRIMARY"), new TableField[] { Topics.TOPICS.ID }, true);
    public static final UniqueKey<TopicsRecord> KEY_TOPICS_SLUG = Internal.createUniqueKey(Topics.TOPICS, DSL.name("KEY_topics_slug"), new TableField[] { Topics.TOPICS.SLUG }, true);
    public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = Internal.createUniqueKey(Users.USERS, DSL.name("KEY_users_PRIMARY"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<UsersRecord> KEY_USERS_UNIQUE_LEETCODE_USERNAME = Internal.createUniqueKey(Users.USERS, DSL.name("KEY_users_unique_leetcode_username"), new TableField[] { Users.USERS.LEETCODE_USERNAME }, true);
    public static final UniqueKey<UsersRecord> KEY_USERS_USERS_USERNAME_KEY = Internal.createUniqueKey(Users.USERS, DSL.name("KEY_users_users_username_key"), new TableField[] { Users.USERS.USERNAME }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<DeckProblemsRecord, DecksRecord> FK_DECK_PROBLEMS_DECK = Internal.createForeignKey(DeckProblems.DECK_PROBLEMS, DSL.name("fk_deck_problems_deck"), new TableField[] { DeckProblems.DECK_PROBLEMS.DECK_ID }, Keys.KEY_DECKS_PRIMARY, new TableField[] { Decks.DECKS.ID }, true);
    public static final ForeignKey<DeckProblemsRecord, ProblemsRecord> FK_DECK_PROBLEMS_PROBLEM = Internal.createForeignKey(DeckProblems.DECK_PROBLEMS, DSL.name("fk_deck_problems_problem"), new TableField[] { DeckProblems.DECK_PROBLEMS.PROBLEM_ID }, Keys.KEY_PROBLEMS_PRIMARY, new TableField[] { Problems.PROBLEMS.ID }, true);
    public static final ForeignKey<DecksRecord, UsersRecord> FK_DECK_USER = Internal.createForeignKey(Decks.DECKS, DSL.name("fk_deck_user"), new TableField[] { Decks.DECKS.USER_ID }, Keys.KEY_USERS_PRIMARY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<FlashcardReviewsRecord, DecksRecord> FK_FLASHCARD_DECK = Internal.createForeignKey(FlashcardReviews.FLASHCARD_REVIEWS, DSL.name("fk_flashcard_deck"), new TableField[] { FlashcardReviews.FLASHCARD_REVIEWS.DECK_ID }, Keys.KEY_DECKS_PRIMARY, new TableField[] { Decks.DECKS.ID }, true);
    public static final ForeignKey<FlashcardReviewsRecord, ProblemsRecord> FK_FLASHCARD_PROBLEM = Internal.createForeignKey(FlashcardReviews.FLASHCARD_REVIEWS, DSL.name("fk_flashcard_problem"), new TableField[] { FlashcardReviews.FLASHCARD_REVIEWS.PROBLEM_ID }, Keys.KEY_PROBLEMS_PRIMARY, new TableField[] { Problems.PROBLEMS.ID }, true);
    public static final ForeignKey<FlashcardReviewsRecord, UsersRecord> FK_FLASHCARD_USER = Internal.createForeignKey(FlashcardReviews.FLASHCARD_REVIEWS, DSL.name("fk_flashcard_user"), new TableField[] { FlashcardReviews.FLASHCARD_REVIEWS.USER_ID }, Keys.KEY_USERS_PRIMARY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<ProblemsTopicRecord, ProblemsRecord> PROBLEMS_TOPIC_IBFK_1 = Internal.createForeignKey(ProblemsTopic.PROBLEMS_TOPIC, DSL.name("problems_topic_ibfk_1"), new TableField[] { ProblemsTopic.PROBLEMS_TOPIC.PROBLEM_ID }, Keys.KEY_PROBLEMS_PRIMARY, new TableField[] { Problems.PROBLEMS.ID }, true);
    public static final ForeignKey<ProblemsTopicRecord, TopicsRecord> PROBLEMS_TOPIC_IBFK_2 = Internal.createForeignKey(ProblemsTopic.PROBLEMS_TOPIC, DSL.name("problems_topic_ibfk_2"), new TableField[] { ProblemsTopic.PROBLEMS_TOPIC.TOPIC_SLUG }, Keys.KEY_TOPICS_SLUG, new TableField[] { Topics.TOPICS.SLUG }, true);
    public static final ForeignKey<ReviewLogsRecord, ProblemsRecord> FK_REVIEW_LOG_PROBLEM = Internal.createForeignKey(ReviewLogs.REVIEW_LOGS, DSL.name("fk_review_log_problem"), new TableField[] { ReviewLogs.REVIEW_LOGS.PROBLEM_ID }, Keys.KEY_PROBLEMS_PRIMARY, new TableField[] { Problems.PROBLEMS.ID }, true);
    public static final ForeignKey<ReviewLogsRecord, UsersRecord> FK_REVIEW_LOG_USER = Internal.createForeignKey(ReviewLogs.REVIEW_LOGS, DSL.name("fk_review_log_user"), new TableField[] { ReviewLogs.REVIEW_LOGS.USER_ID }, Keys.KEY_USERS_PRIMARY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<ReviewSchedulesRecord, ProblemsRecord> FK_REVIEW_PROBLEM = Internal.createForeignKey(ReviewSchedules.REVIEW_SCHEDULES, DSL.name("fk_review_problem"), new TableField[] { ReviewSchedules.REVIEW_SCHEDULES.PROBLEM_ID }, Keys.KEY_PROBLEMS_PRIMARY, new TableField[] { Problems.PROBLEMS.ID }, true);
    public static final ForeignKey<ReviewSchedulesRecord, UsersRecord> FK_REVIEW_USER = Internal.createForeignKey(ReviewSchedules.REVIEW_SCHEDULES, DSL.name("fk_review_user"), new TableField[] { ReviewSchedules.REVIEW_SCHEDULES.USER_ID }, Keys.KEY_USERS_PRIMARY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<SolutionsRecord, ProblemsRecord> FK_SOLUTION_PROBLEM = Internal.createForeignKey(Solutions.SOLUTIONS, DSL.name("fk_solution_problem"), new TableField[] { Solutions.SOLUTIONS.PROBLEM_ID }, Keys.KEY_PROBLEMS_PRIMARY, new TableField[] { Problems.PROBLEMS.ID }, true);
    public static final ForeignKey<SubmissionsRecord, UsersRecord> FK_USER = Internal.createForeignKey(Submissions.SUBMISSIONS, DSL.name("fk_user"), new TableField[] { Submissions.SUBMISSIONS.USER_ID }, Keys.KEY_USERS_PRIMARY, new TableField[] { Users.USERS.ID }, true);
}
