/*
 * This file is generated by jOOQ.
 */
package com.litdeck.backend.jooq;


import com.litdeck.backend.jooq.tables.DeckProblems;
import com.litdeck.backend.jooq.tables.Decks;
import com.litdeck.backend.jooq.tables.FlashcardReviews;
import com.litdeck.backend.jooq.tables.Problems;
import com.litdeck.backend.jooq.tables.ProblemsTopic;
import com.litdeck.backend.jooq.tables.ReviewLogs;
import com.litdeck.backend.jooq.tables.ReviewSchedules;
import com.litdeck.backend.jooq.tables.Solutions;
import com.litdeck.backend.jooq.tables.Submissions;
import com.litdeck.backend.jooq.tables.Topics;
import com.litdeck.backend.jooq.tables.Users;


/**
 * Convenience access to all tables in litdeck.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>litdeck.deck_problems</code>.
     */
    public static final DeckProblems DECK_PROBLEMS = DeckProblems.DECK_PROBLEMS;

    /**
     * The table <code>litdeck.decks</code>.
     */
    public static final Decks DECKS = Decks.DECKS;

    /**
     * The table <code>litdeck.flashcard_reviews</code>.
     */
    public static final FlashcardReviews FLASHCARD_REVIEWS = FlashcardReviews.FLASHCARD_REVIEWS;

    /**
     * The table <code>litdeck.problems</code>.
     */
    public static final Problems PROBLEMS = Problems.PROBLEMS;

    /**
     * The table <code>litdeck.problems_topic</code>.
     */
    public static final ProblemsTopic PROBLEMS_TOPIC = ProblemsTopic.PROBLEMS_TOPIC;

    /**
     * The table <code>litdeck.review_logs</code>.
     */
    public static final ReviewLogs REVIEW_LOGS = ReviewLogs.REVIEW_LOGS;

    /**
     * The table <code>litdeck.review_schedules</code>.
     */
    public static final ReviewSchedules REVIEW_SCHEDULES = ReviewSchedules.REVIEW_SCHEDULES;

    /**
     * The table <code>litdeck.solutions</code>.
     */
    public static final Solutions SOLUTIONS = Solutions.SOLUTIONS;

    /**
     * The table <code>litdeck.submissions</code>.
     */
    public static final Submissions SUBMISSIONS = Submissions.SUBMISSIONS;

    /**
     * The table <code>litdeck.topics</code>.
     */
    public static final Topics TOPICS = Topics.TOPICS;

    /**
     * The table <code>litdeck.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
