/*
 * This file is generated by jOOQ.
 */
package com.litdeck.backend.jooq.tables;


import com.litdeck.backend.jooq.Indexes;
import com.litdeck.backend.jooq.Keys;
import com.litdeck.backend.jooq.Litdeck;
import com.litdeck.backend.jooq.tables.Decks.DecksPath;
import com.litdeck.backend.jooq.tables.Problems.ProblemsPath;
import com.litdeck.backend.jooq.tables.records.DeckProblemsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DeckProblems extends TableImpl<DeckProblemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>litdeck.deck_problems</code>
     */
    public static final DeckProblems DECK_PROBLEMS = new DeckProblems();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DeckProblemsRecord> getRecordType() {
        return DeckProblemsRecord.class;
    }

    /**
     * The column <code>litdeck.deck_problems.deck_id</code>.
     */
    public final TableField<DeckProblemsRecord, Integer> DECK_ID = createField(DSL.name("deck_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>litdeck.deck_problems.problem_id</code>.
     */
    public final TableField<DeckProblemsRecord, Integer> PROBLEM_ID = createField(DSL.name("problem_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>litdeck.deck_problems.added_at</code>.
     */
    public final TableField<DeckProblemsRecord, LocalDateTime> ADDED_AT = createField(DSL.name("added_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private DeckProblems(Name alias, Table<DeckProblemsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DeckProblems(Name alias, Table<DeckProblemsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>litdeck.deck_problems</code> table reference
     */
    public DeckProblems(String alias) {
        this(DSL.name(alias), DECK_PROBLEMS);
    }

    /**
     * Create an aliased <code>litdeck.deck_problems</code> table reference
     */
    public DeckProblems(Name alias) {
        this(alias, DECK_PROBLEMS);
    }

    /**
     * Create a <code>litdeck.deck_problems</code> table reference
     */
    public DeckProblems() {
        this(DSL.name("deck_problems"), null);
    }

    public <O extends Record> DeckProblems(Table<O> path, ForeignKey<O, DeckProblemsRecord> childPath, InverseForeignKey<O, DeckProblemsRecord> parentPath) {
        super(path, childPath, parentPath, DECK_PROBLEMS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class DeckProblemsPath extends DeckProblems implements Path<DeckProblemsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DeckProblemsPath(Table<O> path, ForeignKey<O, DeckProblemsRecord> childPath, InverseForeignKey<O, DeckProblemsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private DeckProblemsPath(Name alias, Table<DeckProblemsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public DeckProblemsPath as(String alias) {
            return new DeckProblemsPath(DSL.name(alias), this);
        }

        @Override
        public DeckProblemsPath as(Name alias) {
            return new DeckProblemsPath(alias, this);
        }

        @Override
        public DeckProblemsPath as(Table<?> alias) {
            return new DeckProblemsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Litdeck.LITDECK;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.DECK_PROBLEMS_IDX_DECK_PROBLEMS_DECK_ID, Indexes.DECK_PROBLEMS_IDX_DECK_PROBLEMS_PROBLEM_ID);
    }

    @Override
    public UniqueKey<DeckProblemsRecord> getPrimaryKey() {
        return Keys.KEY_DECK_PROBLEMS_PRIMARY;
    }

    @Override
    public List<ForeignKey<DeckProblemsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_DECK_PROBLEMS_DECK, Keys.FK_DECK_PROBLEMS_PROBLEM);
    }

    private transient DecksPath _decks;

    /**
     * Get the implicit join path to the <code>litdeck.decks</code> table.
     */
    public DecksPath decks() {
        if (_decks == null)
            _decks = new DecksPath(this, Keys.FK_DECK_PROBLEMS_DECK, null);

        return _decks;
    }

    private transient ProblemsPath _problems;

    /**
     * Get the implicit join path to the <code>litdeck.problems</code> table.
     */
    public ProblemsPath problems() {
        if (_problems == null)
            _problems = new ProblemsPath(this, Keys.FK_DECK_PROBLEMS_PROBLEM, null);

        return _problems;
    }

    @Override
    public DeckProblems as(String alias) {
        return new DeckProblems(DSL.name(alias), this);
    }

    @Override
    public DeckProblems as(Name alias) {
        return new DeckProblems(alias, this);
    }

    @Override
    public DeckProblems as(Table<?> alias) {
        return new DeckProblems(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DeckProblems rename(String name) {
        return new DeckProblems(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DeckProblems rename(Name name) {
        return new DeckProblems(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DeckProblems rename(Table<?> name) {
        return new DeckProblems(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DeckProblems where(Condition condition) {
        return new DeckProblems(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DeckProblems where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DeckProblems where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DeckProblems where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DeckProblems where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DeckProblems where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DeckProblems where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DeckProblems where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DeckProblems whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DeckProblems whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
