/*
 * This file is generated by jOOQ.
 */
package com.litdeck.backend.jooq.tables;


import com.litdeck.backend.jooq.Indexes;
import com.litdeck.backend.jooq.Keys;
import com.litdeck.backend.jooq.Litdeck;
import com.litdeck.backend.jooq.tables.Decks.DecksPath;
import com.litdeck.backend.jooq.tables.Problems.ProblemsPath;
import com.litdeck.backend.jooq.tables.Users.UsersPath;
import com.litdeck.backend.jooq.tables.records.FlashcardReviewsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FlashcardReviews extends TableImpl<FlashcardReviewsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>litdeck.flashcard_reviews</code>
     */
    public static final FlashcardReviews FLASHCARD_REVIEWS = new FlashcardReviews();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FlashcardReviewsRecord> getRecordType() {
        return FlashcardReviewsRecord.class;
    }

    /**
     * The column <code>litdeck.flashcard_reviews.id</code>.
     */
    public final TableField<FlashcardReviewsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>litdeck.flashcard_reviews.user_id</code>.
     */
    public final TableField<FlashcardReviewsRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.CHAR(36).nullable(false), this, "");

    /**
     * The column <code>litdeck.flashcard_reviews.deck_id</code>.
     */
    public final TableField<FlashcardReviewsRecord, Integer> DECK_ID = createField(DSL.name("deck_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>litdeck.flashcard_reviews.problem_id</code>.
     */
    public final TableField<FlashcardReviewsRecord, Integer> PROBLEM_ID = createField(DSL.name("problem_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>litdeck.flashcard_reviews.due_date</code>.
     */
    public final TableField<FlashcardReviewsRecord, LocalDateTime> DUE_DATE = createField(DSL.name("due_date"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>litdeck.flashcard_reviews.stability</code>.
     */
    public final TableField<FlashcardReviewsRecord, Double> STABILITY = createField(DSL.name("stability"), SQLDataType.FLOAT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.FLOAT)), this, "");

    /**
     * The column <code>litdeck.flashcard_reviews.difficulty</code>.
     */
    public final TableField<FlashcardReviewsRecord, Double> DIFFICULTY = createField(DSL.name("difficulty"), SQLDataType.FLOAT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.FLOAT)), this, "");

    /**
     * The column <code>litdeck.flashcard_reviews.elapsed_days</code>.
     */
    public final TableField<FlashcardReviewsRecord, Integer> ELAPSED_DAYS = createField(DSL.name("elapsed_days"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>litdeck.flashcard_reviews.scheduled_days</code>.
     */
    public final TableField<FlashcardReviewsRecord, Integer> SCHEDULED_DAYS = createField(DSL.name("scheduled_days"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>litdeck.flashcard_reviews.reps</code>.
     */
    public final TableField<FlashcardReviewsRecord, Integer> REPS = createField(DSL.name("reps"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>litdeck.flashcard_reviews.lapses</code>.
     */
    public final TableField<FlashcardReviewsRecord, Integer> LAPSES = createField(DSL.name("lapses"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>litdeck.flashcard_reviews.state</code>.
     */
    public final TableField<FlashcardReviewsRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(50).nullable(false).defaultValue(DSL.inline("new", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>litdeck.flashcard_reviews.last_review</code>.
     */
    public final TableField<FlashcardReviewsRecord, LocalDateTime> LAST_REVIEW = createField(DSL.name("last_review"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>litdeck.flashcard_reviews.created_at</code>.
     */
    public final TableField<FlashcardReviewsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>litdeck.flashcard_reviews.updated_at</code>.
     */
    public final TableField<FlashcardReviewsRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private FlashcardReviews(Name alias, Table<FlashcardReviewsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FlashcardReviews(Name alias, Table<FlashcardReviewsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>litdeck.flashcard_reviews</code> table reference
     */
    public FlashcardReviews(String alias) {
        this(DSL.name(alias), FLASHCARD_REVIEWS);
    }

    /**
     * Create an aliased <code>litdeck.flashcard_reviews</code> table reference
     */
    public FlashcardReviews(Name alias) {
        this(alias, FLASHCARD_REVIEWS);
    }

    /**
     * Create a <code>litdeck.flashcard_reviews</code> table reference
     */
    public FlashcardReviews() {
        this(DSL.name("flashcard_reviews"), null);
    }

    public <O extends Record> FlashcardReviews(Table<O> path, ForeignKey<O, FlashcardReviewsRecord> childPath, InverseForeignKey<O, FlashcardReviewsRecord> parentPath) {
        super(path, childPath, parentPath, FLASHCARD_REVIEWS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class FlashcardReviewsPath extends FlashcardReviews implements Path<FlashcardReviewsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> FlashcardReviewsPath(Table<O> path, ForeignKey<O, FlashcardReviewsRecord> childPath, InverseForeignKey<O, FlashcardReviewsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private FlashcardReviewsPath(Name alias, Table<FlashcardReviewsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public FlashcardReviewsPath as(String alias) {
            return new FlashcardReviewsPath(DSL.name(alias), this);
        }

        @Override
        public FlashcardReviewsPath as(Name alias) {
            return new FlashcardReviewsPath(alias, this);
        }

        @Override
        public FlashcardReviewsPath as(Table<?> alias) {
            return new FlashcardReviewsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Litdeck.LITDECK;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.FLASHCARD_REVIEWS_IDX_FLASHCARD_REVIEWS_DECK_ID, Indexes.FLASHCARD_REVIEWS_IDX_FLASHCARD_REVIEWS_DUE_DATE, Indexes.FLASHCARD_REVIEWS_IDX_FLASHCARD_REVIEWS_USER_DUE, Indexes.FLASHCARD_REVIEWS_IDX_FLASHCARD_REVIEWS_USER_ID);
    }

    @Override
    public Identity<FlashcardReviewsRecord, Integer> getIdentity() {
        return (Identity<FlashcardReviewsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<FlashcardReviewsRecord> getPrimaryKey() {
        return Keys.KEY_FLASHCARD_REVIEWS_PRIMARY;
    }

    @Override
    public List<UniqueKey<FlashcardReviewsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_FLASHCARD_REVIEWS_UNIQUE_USER_DECK_PROBLEM);
    }

    @Override
    public List<ForeignKey<FlashcardReviewsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_FLASHCARD_DECK, Keys.FK_FLASHCARD_PROBLEM, Keys.FK_FLASHCARD_USER);
    }

    private transient DecksPath _decks;

    /**
     * Get the implicit join path to the <code>litdeck.decks</code> table.
     */
    public DecksPath decks() {
        if (_decks == null)
            _decks = new DecksPath(this, Keys.FK_FLASHCARD_DECK, null);

        return _decks;
    }

    private transient ProblemsPath _problems;

    /**
     * Get the implicit join path to the <code>litdeck.problems</code> table.
     */
    public ProblemsPath problems() {
        if (_problems == null)
            _problems = new ProblemsPath(this, Keys.FK_FLASHCARD_PROBLEM, null);

        return _problems;
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>litdeck.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.FK_FLASHCARD_USER, null);

        return _users;
    }

    @Override
    public FlashcardReviews as(String alias) {
        return new FlashcardReviews(DSL.name(alias), this);
    }

    @Override
    public FlashcardReviews as(Name alias) {
        return new FlashcardReviews(alias, this);
    }

    @Override
    public FlashcardReviews as(Table<?> alias) {
        return new FlashcardReviews(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FlashcardReviews rename(String name) {
        return new FlashcardReviews(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FlashcardReviews rename(Name name) {
        return new FlashcardReviews(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FlashcardReviews rename(Table<?> name) {
        return new FlashcardReviews(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FlashcardReviews where(Condition condition) {
        return new FlashcardReviews(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FlashcardReviews where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FlashcardReviews where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FlashcardReviews where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FlashcardReviews where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FlashcardReviews where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FlashcardReviews where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FlashcardReviews where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FlashcardReviews whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FlashcardReviews whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
