/*
 * This file is generated by jOOQ.
 */
package com.litdeck.backend.jooq.tables;


import com.litdeck.backend.jooq.Indexes;
import com.litdeck.backend.jooq.Keys;
import com.litdeck.backend.jooq.Litdeck;
import com.litdeck.backend.jooq.tables.Problems.ProblemsPath;
import com.litdeck.backend.jooq.tables.Users.UsersPath;
import com.litdeck.backend.jooq.tables.records.ReviewSchedulesRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReviewSchedules extends TableImpl<ReviewSchedulesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>litdeck.review_schedules</code>
     */
    public static final ReviewSchedules REVIEW_SCHEDULES = new ReviewSchedules();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReviewSchedulesRecord> getRecordType() {
        return ReviewSchedulesRecord.class;
    }

    /**
     * The column <code>litdeck.review_schedules.id</code>.
     */
    public final TableField<ReviewSchedulesRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>litdeck.review_schedules.user_id</code>.
     */
    public final TableField<ReviewSchedulesRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.CHAR(36).nullable(false), this, "");

    /**
     * The column <code>litdeck.review_schedules.problem_id</code>.
     */
    public final TableField<ReviewSchedulesRecord, Integer> PROBLEM_ID = createField(DSL.name("problem_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>litdeck.review_schedules.due_date</code>.
     */
    public final TableField<ReviewSchedulesRecord, LocalDateTime> DUE_DATE = createField(DSL.name("due_date"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>litdeck.review_schedules.stability</code>.
     */
    public final TableField<ReviewSchedulesRecord, Double> STABILITY = createField(DSL.name("stability"), SQLDataType.FLOAT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.FLOAT)), this, "");

    /**
     * The column <code>litdeck.review_schedules.difficulty</code>.
     */
    public final TableField<ReviewSchedulesRecord, Double> DIFFICULTY = createField(DSL.name("difficulty"), SQLDataType.FLOAT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.FLOAT)), this, "");

    /**
     * The column <code>litdeck.review_schedules.elapsed_days</code>.
     */
    public final TableField<ReviewSchedulesRecord, Integer> ELAPSED_DAYS = createField(DSL.name("elapsed_days"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>litdeck.review_schedules.scheduled_days</code>.
     */
    public final TableField<ReviewSchedulesRecord, Integer> SCHEDULED_DAYS = createField(DSL.name("scheduled_days"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>litdeck.review_schedules.reps</code>.
     */
    public final TableField<ReviewSchedulesRecord, Integer> REPS = createField(DSL.name("reps"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>litdeck.review_schedules.lapses</code>.
     */
    public final TableField<ReviewSchedulesRecord, Integer> LAPSES = createField(DSL.name("lapses"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>litdeck.review_schedules.state</code>.
     */
    public final TableField<ReviewSchedulesRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(50).nullable(false).defaultValue(DSL.inline("new", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>litdeck.review_schedules.last_review</code>.
     */
    public final TableField<ReviewSchedulesRecord, LocalDateTime> LAST_REVIEW = createField(DSL.name("last_review"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>litdeck.review_schedules.created_at</code>.
     */
    public final TableField<ReviewSchedulesRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>litdeck.review_schedules.updated_at</code>.
     */
    public final TableField<ReviewSchedulesRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private ReviewSchedules(Name alias, Table<ReviewSchedulesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ReviewSchedules(Name alias, Table<ReviewSchedulesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>litdeck.review_schedules</code> table reference
     */
    public ReviewSchedules(String alias) {
        this(DSL.name(alias), REVIEW_SCHEDULES);
    }

    /**
     * Create an aliased <code>litdeck.review_schedules</code> table reference
     */
    public ReviewSchedules(Name alias) {
        this(alias, REVIEW_SCHEDULES);
    }

    /**
     * Create a <code>litdeck.review_schedules</code> table reference
     */
    public ReviewSchedules() {
        this(DSL.name("review_schedules"), null);
    }

    public <O extends Record> ReviewSchedules(Table<O> path, ForeignKey<O, ReviewSchedulesRecord> childPath, InverseForeignKey<O, ReviewSchedulesRecord> parentPath) {
        super(path, childPath, parentPath, REVIEW_SCHEDULES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReviewSchedulesPath extends ReviewSchedules implements Path<ReviewSchedulesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ReviewSchedulesPath(Table<O> path, ForeignKey<O, ReviewSchedulesRecord> childPath, InverseForeignKey<O, ReviewSchedulesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReviewSchedulesPath(Name alias, Table<ReviewSchedulesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReviewSchedulesPath as(String alias) {
            return new ReviewSchedulesPath(DSL.name(alias), this);
        }

        @Override
        public ReviewSchedulesPath as(Name alias) {
            return new ReviewSchedulesPath(alias, this);
        }

        @Override
        public ReviewSchedulesPath as(Table<?> alias) {
            return new ReviewSchedulesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Litdeck.LITDECK;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.REVIEW_SCHEDULES_IDX_REVIEW_SCHEDULES_DUE_DATE, Indexes.REVIEW_SCHEDULES_IDX_REVIEW_SCHEDULES_USER_DUE, Indexes.REVIEW_SCHEDULES_IDX_REVIEW_SCHEDULES_USER_ID);
    }

    @Override
    public Identity<ReviewSchedulesRecord, Integer> getIdentity() {
        return (Identity<ReviewSchedulesRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReviewSchedulesRecord> getPrimaryKey() {
        return Keys.KEY_REVIEW_SCHEDULES_PRIMARY;
    }

    @Override
    public List<UniqueKey<ReviewSchedulesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_REVIEW_SCHEDULES_UNIQUE_USER_PROBLEM);
    }

    @Override
    public List<ForeignKey<ReviewSchedulesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_REVIEW_PROBLEM, Keys.FK_REVIEW_USER);
    }

    private transient ProblemsPath _problems;

    /**
     * Get the implicit join path to the <code>litdeck.problems</code> table.
     */
    public ProblemsPath problems() {
        if (_problems == null)
            _problems = new ProblemsPath(this, Keys.FK_REVIEW_PROBLEM, null);

        return _problems;
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>litdeck.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.FK_REVIEW_USER, null);

        return _users;
    }

    @Override
    public ReviewSchedules as(String alias) {
        return new ReviewSchedules(DSL.name(alias), this);
    }

    @Override
    public ReviewSchedules as(Name alias) {
        return new ReviewSchedules(alias, this);
    }

    @Override
    public ReviewSchedules as(Table<?> alias) {
        return new ReviewSchedules(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReviewSchedules rename(String name) {
        return new ReviewSchedules(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReviewSchedules rename(Name name) {
        return new ReviewSchedules(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReviewSchedules rename(Table<?> name) {
        return new ReviewSchedules(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReviewSchedules where(Condition condition) {
        return new ReviewSchedules(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReviewSchedules where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReviewSchedules where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReviewSchedules where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReviewSchedules where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReviewSchedules where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReviewSchedules where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReviewSchedules where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReviewSchedules whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReviewSchedules whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
