/*
 * This file is generated by jOOQ.
 */
package com.litdeck.backend.jooq.tables;


import com.litdeck.backend.jooq.Indexes;
import com.litdeck.backend.jooq.Keys;
import com.litdeck.backend.jooq.Litdeck;
import com.litdeck.backend.jooq.tables.Problems.ProblemsPath;
import com.litdeck.backend.jooq.tables.records.SolutionsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Solutions extends TableImpl<SolutionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>litdeck.solutions</code>
     */
    public static final Solutions SOLUTIONS = new Solutions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SolutionsRecord> getRecordType() {
        return SolutionsRecord.class;
    }

    /**
     * The column <code>litdeck.solutions.id</code>.
     */
    public final TableField<SolutionsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>litdeck.solutions.problem_id</code>.
     */
    public final TableField<SolutionsRecord, Integer> PROBLEM_ID = createField(DSL.name("problem_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>litdeck.solutions.title</code>.
     */
    public final TableField<SolutionsRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>litdeck.solutions.language</code>.
     */
    public final TableField<SolutionsRecord, String> LANGUAGE = createField(DSL.name("language"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>litdeck.solutions.code</code>.
     */
    public final TableField<SolutionsRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>litdeck.solutions.explanation</code>.
     */
    public final TableField<SolutionsRecord, String> EXPLANATION = createField(DSL.name("explanation"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>litdeck.solutions.time_complexity</code>.
     */
    public final TableField<SolutionsRecord, String> TIME_COMPLEXITY = createField(DSL.name("time_complexity"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>litdeck.solutions.space_complexity</code>.
     */
    public final TableField<SolutionsRecord, String> SPACE_COMPLEXITY = createField(DSL.name("space_complexity"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>litdeck.solutions.is_optimal</code>.
     */
    public final TableField<SolutionsRecord, Byte> IS_OPTIMAL = createField(DSL.name("is_optimal"), SQLDataType.TINYINT.defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>litdeck.solutions.created_at</code>.
     */
    public final TableField<SolutionsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>litdeck.solutions.updated_at</code>.
     */
    public final TableField<SolutionsRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private Solutions(Name alias, Table<SolutionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Solutions(Name alias, Table<SolutionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>litdeck.solutions</code> table reference
     */
    public Solutions(String alias) {
        this(DSL.name(alias), SOLUTIONS);
    }

    /**
     * Create an aliased <code>litdeck.solutions</code> table reference
     */
    public Solutions(Name alias) {
        this(alias, SOLUTIONS);
    }

    /**
     * Create a <code>litdeck.solutions</code> table reference
     */
    public Solutions() {
        this(DSL.name("solutions"), null);
    }

    public <O extends Record> Solutions(Table<O> path, ForeignKey<O, SolutionsRecord> childPath, InverseForeignKey<O, SolutionsRecord> parentPath) {
        super(path, childPath, parentPath, SOLUTIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SolutionsPath extends Solutions implements Path<SolutionsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SolutionsPath(Table<O> path, ForeignKey<O, SolutionsRecord> childPath, InverseForeignKey<O, SolutionsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SolutionsPath(Name alias, Table<SolutionsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SolutionsPath as(String alias) {
            return new SolutionsPath(DSL.name(alias), this);
        }

        @Override
        public SolutionsPath as(Name alias) {
            return new SolutionsPath(alias, this);
        }

        @Override
        public SolutionsPath as(Table<?> alias) {
            return new SolutionsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Litdeck.LITDECK;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SOLUTIONS_IDX_SOLUTIONS_LANGUAGE, Indexes.SOLUTIONS_IDX_SOLUTIONS_PROBLEM_ID);
    }

    @Override
    public Identity<SolutionsRecord, Integer> getIdentity() {
        return (Identity<SolutionsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<SolutionsRecord> getPrimaryKey() {
        return Keys.KEY_SOLUTIONS_PRIMARY;
    }

    @Override
    public List<ForeignKey<SolutionsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_SOLUTION_PROBLEM);
    }

    private transient ProblemsPath _problems;

    /**
     * Get the implicit join path to the <code>litdeck.problems</code> table.
     */
    public ProblemsPath problems() {
        if (_problems == null)
            _problems = new ProblemsPath(this, Keys.FK_SOLUTION_PROBLEM, null);

        return _problems;
    }

    @Override
    public Solutions as(String alias) {
        return new Solutions(DSL.name(alias), this);
    }

    @Override
    public Solutions as(Name alias) {
        return new Solutions(alias, this);
    }

    @Override
    public Solutions as(Table<?> alias) {
        return new Solutions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Solutions rename(String name) {
        return new Solutions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Solutions rename(Name name) {
        return new Solutions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Solutions rename(Table<?> name) {
        return new Solutions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Solutions where(Condition condition) {
        return new Solutions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Solutions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Solutions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Solutions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Solutions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Solutions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Solutions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Solutions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Solutions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Solutions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
