/*
 * This file is generated by jOOQ.
 */
package com.litdeck.backend.jooq.tables;


import com.litdeck.backend.jooq.Keys;
import com.litdeck.backend.jooq.Litdeck;
import com.litdeck.backend.jooq.tables.Problems.ProblemsPath;
import com.litdeck.backend.jooq.tables.ProblemsTopic.ProblemsTopicPath;
import com.litdeck.backend.jooq.tables.records.TopicsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Topics extends TableImpl<TopicsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>litdeck.topics</code>
     */
    public static final Topics TOPICS = new Topics();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TopicsRecord> getRecordType() {
        return TopicsRecord.class;
    }

    /**
     * The column <code>litdeck.topics.id</code>.
     */
    public final TableField<TopicsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>litdeck.topics.name</code>.
     */
    public final TableField<TopicsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>litdeck.topics.slug</code>.
     */
    public final TableField<TopicsRecord, String> SLUG = createField(DSL.name("slug"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>litdeck.topics.created_at</code>.
     */
    public final TableField<TopicsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private Topics(Name alias, Table<TopicsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Topics(Name alias, Table<TopicsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>litdeck.topics</code> table reference
     */
    public Topics(String alias) {
        this(DSL.name(alias), TOPICS);
    }

    /**
     * Create an aliased <code>litdeck.topics</code> table reference
     */
    public Topics(Name alias) {
        this(alias, TOPICS);
    }

    /**
     * Create a <code>litdeck.topics</code> table reference
     */
    public Topics() {
        this(DSL.name("topics"), null);
    }

    public <O extends Record> Topics(Table<O> path, ForeignKey<O, TopicsRecord> childPath, InverseForeignKey<O, TopicsRecord> parentPath) {
        super(path, childPath, parentPath, TOPICS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TopicsPath extends Topics implements Path<TopicsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TopicsPath(Table<O> path, ForeignKey<O, TopicsRecord> childPath, InverseForeignKey<O, TopicsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TopicsPath(Name alias, Table<TopicsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TopicsPath as(String alias) {
            return new TopicsPath(DSL.name(alias), this);
        }

        @Override
        public TopicsPath as(Name alias) {
            return new TopicsPath(alias, this);
        }

        @Override
        public TopicsPath as(Table<?> alias) {
            return new TopicsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Litdeck.LITDECK;
    }

    @Override
    public Identity<TopicsRecord, Integer> getIdentity() {
        return (Identity<TopicsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TopicsRecord> getPrimaryKey() {
        return Keys.KEY_TOPICS_PRIMARY;
    }

    @Override
    public List<UniqueKey<TopicsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_TOPICS_NAME, Keys.KEY_TOPICS_SLUG);
    }

    private transient ProblemsTopicPath _problemsTopic;

    /**
     * Get the implicit to-many join path to the
     * <code>litdeck.problems_topic</code> table
     */
    public ProblemsTopicPath problemsTopic() {
        if (_problemsTopic == null)
            _problemsTopic = new ProblemsTopicPath(this, null, Keys.PROBLEMS_TOPIC_IBFK_2.getInverseKey());

        return _problemsTopic;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>litdeck.problems</code> table
     */
    public ProblemsPath problems() {
        return problemsTopic().problems();
    }

    @Override
    public Topics as(String alias) {
        return new Topics(DSL.name(alias), this);
    }

    @Override
    public Topics as(Name alias) {
        return new Topics(alias, this);
    }

    @Override
    public Topics as(Table<?> alias) {
        return new Topics(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Topics rename(String name) {
        return new Topics(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Topics rename(Name name) {
        return new Topics(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Topics rename(Table<?> name) {
        return new Topics(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Topics where(Condition condition) {
        return new Topics(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Topics where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Topics where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Topics where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Topics where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Topics where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Topics where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Topics where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Topics whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Topics whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
