/*
 * This file is generated by jOOQ.
 */
package com.litdeck.backend.jooq.tables;


import com.litdeck.backend.jooq.Keys;
import com.litdeck.backend.jooq.Litdeck;
import com.litdeck.backend.jooq.tables.Decks.DecksPath;
import com.litdeck.backend.jooq.tables.FlashcardReviews.FlashcardReviewsPath;
import com.litdeck.backend.jooq.tables.Problems.ProblemsPath;
import com.litdeck.backend.jooq.tables.ReviewLogs.ReviewLogsPath;
import com.litdeck.backend.jooq.tables.ReviewSchedules.ReviewSchedulesPath;
import com.litdeck.backend.jooq.tables.Submissions.SubmissionsPath;
import com.litdeck.backend.jooq.tables.records.UsersRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Users extends TableImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>litdeck.users</code>
     */
    public static final Users USERS = new Users();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsersRecord> getRecordType() {
        return UsersRecord.class;
    }

    /**
     * The column <code>litdeck.users.id</code>.
     */
    public final TableField<UsersRecord, String> ID = createField(DSL.name("id"), SQLDataType.CHAR(36).nullable(false).defaultValue(DSL.inline("uuid()", SQLDataType.CHAR)), this, "");

    /**
     * The column <code>litdeck.users.email</code>.
     */
    public final TableField<UsersRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>litdeck.users.username</code>.
     */
    public final TableField<UsersRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>litdeck.users.created_at</code>.
     */
    public final TableField<UsersRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>litdeck.users.leetcode_username</code>.
     */
    public final TableField<UsersRecord, String> LEETCODE_USERNAME = createField(DSL.name("leetcode_username"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private Users(Name alias, Table<UsersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Users(Name alias, Table<UsersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>litdeck.users</code> table reference
     */
    public Users(String alias) {
        this(DSL.name(alias), USERS);
    }

    /**
     * Create an aliased <code>litdeck.users</code> table reference
     */
    public Users(Name alias) {
        this(alias, USERS);
    }

    /**
     * Create a <code>litdeck.users</code> table reference
     */
    public Users() {
        this(DSL.name("users"), null);
    }

    public <O extends Record> Users(Table<O> path, ForeignKey<O, UsersRecord> childPath, InverseForeignKey<O, UsersRecord> parentPath) {
        super(path, childPath, parentPath, USERS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UsersPath extends Users implements Path<UsersRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UsersPath(Table<O> path, ForeignKey<O, UsersRecord> childPath, InverseForeignKey<O, UsersRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UsersPath(Name alias, Table<UsersRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UsersPath as(String alias) {
            return new UsersPath(DSL.name(alias), this);
        }

        @Override
        public UsersPath as(Name alias) {
            return new UsersPath(alias, this);
        }

        @Override
        public UsersPath as(Table<?> alias) {
            return new UsersPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Litdeck.LITDECK;
    }

    @Override
    public UniqueKey<UsersRecord> getPrimaryKey() {
        return Keys.KEY_USERS_PRIMARY;
    }

    @Override
    public List<UniqueKey<UsersRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_USERS_UNIQUE_LEETCODE_USERNAME, Keys.KEY_USERS_USERS_USERNAME_KEY);
    }

    private transient DecksPath _decks;

    /**
     * Get the implicit to-many join path to the <code>litdeck.decks</code>
     * table
     */
    public DecksPath decks() {
        if (_decks == null)
            _decks = new DecksPath(this, null, Keys.FK_DECK_USER.getInverseKey());

        return _decks;
    }

    private transient FlashcardReviewsPath _flashcardReviews;

    /**
     * Get the implicit to-many join path to the
     * <code>litdeck.flashcard_reviews</code> table
     */
    public FlashcardReviewsPath flashcardReviews() {
        if (_flashcardReviews == null)
            _flashcardReviews = new FlashcardReviewsPath(this, null, Keys.FK_FLASHCARD_USER.getInverseKey());

        return _flashcardReviews;
    }

    private transient ReviewLogsPath _reviewLogs;

    /**
     * Get the implicit to-many join path to the
     * <code>litdeck.review_logs</code> table
     */
    public ReviewLogsPath reviewLogs() {
        if (_reviewLogs == null)
            _reviewLogs = new ReviewLogsPath(this, null, Keys.FK_REVIEW_LOG_USER.getInverseKey());

        return _reviewLogs;
    }

    private transient ReviewSchedulesPath _reviewSchedules;

    /**
     * Get the implicit to-many join path to the
     * <code>litdeck.review_schedules</code> table
     */
    public ReviewSchedulesPath reviewSchedules() {
        if (_reviewSchedules == null)
            _reviewSchedules = new ReviewSchedulesPath(this, null, Keys.FK_REVIEW_USER.getInverseKey());

        return _reviewSchedules;
    }

    private transient SubmissionsPath _submissions;

    /**
     * Get the implicit to-many join path to the
     * <code>litdeck.submissions</code> table
     */
    public SubmissionsPath submissions() {
        if (_submissions == null)
            _submissions = new SubmissionsPath(this, null, Keys.FK_USER.getInverseKey());

        return _submissions;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>litdeck.problems</code> table
     */
    public ProblemsPath problems() {
        return reviewSchedules().problems();
    }

    @Override
    public Users as(String alias) {
        return new Users(DSL.name(alias), this);
    }

    @Override
    public Users as(Name alias) {
        return new Users(alias, this);
    }

    @Override
    public Users as(Table<?> alias) {
        return new Users(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Users rename(String name) {
        return new Users(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Users rename(Name name) {
        return new Users(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Users rename(Table<?> name) {
        return new Users(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Users where(Condition condition) {
        return new Users(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Users where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Users where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Users where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Users where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Users where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Users where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Users where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Users whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Users whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
