/*
 * This file is generated by jOOQ.
 */
package com.ls.jooq.tables;


import com.ls.jooq.Indexes;
import com.ls.jooq.Keys;
import com.ls.jooq.Leetstack;
import com.ls.jooq.tables.User.UserPath;
import com.ls.jooq.tables.records.UserDsaRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserDsa extends TableImpl<UserDsaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>leetstack.user_dsa</code>
     */
    public static final UserDsa USER_DSA = new UserDsa();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserDsaRecord> getRecordType() {
        return UserDsaRecord.class;
    }

    /**
     * The column <code>leetstack.user_dsa.id</code>.
     */
    public final TableField<UserDsaRecord, ULong> ID = createField(DSL.name("id"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>leetstack.user_dsa.user_id</code>.
     */
    public final TableField<UserDsaRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.CHAR(36).nullable(false), this, "");

    /**
     * The column <code>leetstack.user_dsa.title</code>.
     */
    public final TableField<UserDsaRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>leetstack.user_dsa.title_slug</code>.
     */
    public final TableField<UserDsaRecord, String> TITLE_SLUG = createField(DSL.name("title_slug"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>leetstack.user_dsa.difficulty</code>.
     */
    public final TableField<UserDsaRecord, String> DIFFICULTY = createField(DSL.name("difficulty"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>leetstack.user_dsa.is_paid_only</code>.
     */
    public final TableField<UserDsaRecord, Byte> IS_PAID_ONLY = createField(DSL.name("is_paid_only"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>leetstack.user_dsa.description</code>.
     */
    public final TableField<UserDsaRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>leetstack.user_dsa.solution</code>.
     */
    public final TableField<UserDsaRecord, String> SOLUTION = createField(DSL.name("solution"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>leetstack.user_dsa.note</code>.
     */
    public final TableField<UserDsaRecord, String> NOTE = createField(DSL.name("note"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>leetstack.user_dsa.example_testcases</code>.
     */
    public final TableField<UserDsaRecord, String> EXAMPLE_TESTCASES = createField(DSL.name("example_testcases"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>leetstack.user_dsa.created_date</code>.
     */
    public final TableField<UserDsaRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>leetstack.user_dsa.last_updated_date</code>.
     */
    public final TableField<UserDsaRecord, LocalDateTime> LAST_UPDATED_DATE = createField(DSL.name("last_updated_date"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>leetstack.user_dsa.ideal_solution_code</code>.
     */
    public final TableField<UserDsaRecord, String> IDEAL_SOLUTION_CODE = createField(DSL.name("ideal_solution_code"), SQLDataType.CLOB, this, "");

    private UserDsa(Name alias, Table<UserDsaRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserDsa(Name alias, Table<UserDsaRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>leetstack.user_dsa</code> table reference
     */
    public UserDsa(String alias) {
        this(DSL.name(alias), USER_DSA);
    }

    /**
     * Create an aliased <code>leetstack.user_dsa</code> table reference
     */
    public UserDsa(Name alias) {
        this(alias, USER_DSA);
    }

    /**
     * Create a <code>leetstack.user_dsa</code> table reference
     */
    public UserDsa() {
        this(DSL.name("user_dsa"), null);
    }

    public <O extends Record> UserDsa(Table<O> path, ForeignKey<O, UserDsaRecord> childPath, InverseForeignKey<O, UserDsaRecord> parentPath) {
        super(path, childPath, parentPath, USER_DSA);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UserDsaPath extends UserDsa implements Path<UserDsaRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UserDsaPath(Table<O> path, ForeignKey<O, UserDsaRecord> childPath, InverseForeignKey<O, UserDsaRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UserDsaPath(Name alias, Table<UserDsaRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UserDsaPath as(String alias) {
            return new UserDsaPath(DSL.name(alias), this);
        }

        @Override
        public UserDsaPath as(Name alias) {
            return new UserDsaPath(alias, this);
        }

        @Override
        public UserDsaPath as(Table<?> alias) {
            return new UserDsaPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Leetstack.LEETSTACK;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.USER_DSA_IDX_USER_DSA_TITLE_SLUG, Indexes.USER_DSA_IDX_USER_DSA_USER_ID);
    }

    @Override
    public Identity<UserDsaRecord, ULong> getIdentity() {
        return (Identity<UserDsaRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<UserDsaRecord> getPrimaryKey() {
        return Keys.KEY_USER_DSA_PRIMARY;
    }

    @Override
    public List<UniqueKey<UserDsaRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_USER_DSA_UQ_USER_DSA_USER_SLUG);
    }

    @Override
    public List<ForeignKey<UserDsaRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_USER_DSA_USER);
    }

    private transient UserPath _user;

    /**
     * Get the implicit join path to the <code>leetstack.user</code> table.
     */
    public UserPath user() {
        if (_user == null)
            _user = new UserPath(this, Keys.FK_USER_DSA_USER, null);

        return _user;
    }

    @Override
    public UserDsa as(String alias) {
        return new UserDsa(DSL.name(alias), this);
    }

    @Override
    public UserDsa as(Name alias) {
        return new UserDsa(alias, this);
    }

    @Override
    public UserDsa as(Table<?> alias) {
        return new UserDsa(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserDsa rename(String name) {
        return new UserDsa(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserDsa rename(Name name) {
        return new UserDsa(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserDsa rename(Table<?> name) {
        return new UserDsa(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserDsa where(Condition condition) {
        return new UserDsa(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserDsa where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserDsa where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserDsa where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserDsa where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserDsa where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserDsa where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserDsa where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserDsa whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserDsa whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
