/*
 * This file is generated by jOOQ.
 */
package com.ls.jooq.tables;


import com.ls.jooq.DefaultSchema;
import com.ls.jooq.Indexes;
import com.ls.jooq.Keys;
import com.ls.jooq.tables.User.UserPath;
import com.ls.jooq.tables.records.UserApiKeyRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserApiKey extends TableImpl<UserApiKeyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>user_api_key</code>
     */
    public static final UserApiKey USER_API_KEY = new UserApiKey();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserApiKeyRecord> getRecordType() {
        return UserApiKeyRecord.class;
    }

    /**
     * The column <code>user_api_key.id</code>.
     */
    public final TableField<UserApiKeyRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.identity(true), this, "");

    /**
     * The column <code>user_api_key.user_id</code>.
     */
    public final TableField<UserApiKeyRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>user_api_key.key_hash</code>.
     */
    public final TableField<UserApiKeyRecord, String> KEY_HASH = createField(DSL.name("key_hash"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>user_api_key.label</code>.
     */
    public final TableField<UserApiKeyRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>user_api_key.revoked</code>.
     */
    public final TableField<UserApiKeyRecord, Integer> REVOKED = createField(DSL.name("revoked"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>user_api_key.created_date</code>.
     */
    public final TableField<UserApiKeyRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>user_api_key.last_used_date</code>.
     */
    public final TableField<UserApiKeyRecord, LocalDateTime> LAST_USED_DATE = createField(DSL.name("last_used_date"), SQLDataType.LOCALDATETIME(0), this, "");

    private UserApiKey(Name alias, Table<UserApiKeyRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserApiKey(Name alias, Table<UserApiKeyRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>user_api_key</code> table reference
     */
    public UserApiKey(String alias) {
        this(DSL.name(alias), USER_API_KEY);
    }

    /**
     * Create an aliased <code>user_api_key</code> table reference
     */
    public UserApiKey(Name alias) {
        this(alias, USER_API_KEY);
    }

    /**
     * Create a <code>user_api_key</code> table reference
     */
    public UserApiKey() {
        this(DSL.name("user_api_key"), null);
    }

    public <O extends Record> UserApiKey(Table<O> path, ForeignKey<O, UserApiKeyRecord> childPath, InverseForeignKey<O, UserApiKeyRecord> parentPath) {
        super(path, childPath, parentPath, USER_API_KEY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UserApiKeyPath extends UserApiKey implements Path<UserApiKeyRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UserApiKeyPath(Table<O> path, ForeignKey<O, UserApiKeyRecord> childPath, InverseForeignKey<O, UserApiKeyRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UserApiKeyPath(Name alias, Table<UserApiKeyRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UserApiKeyPath as(String alias) {
            return new UserApiKeyPath(DSL.name(alias), this);
        }

        @Override
        public UserApiKeyPath as(Name alias) {
            return new UserApiKeyPath(alias, this);
        }

        @Override
        public UserApiKeyPath as(Table<?> alias) {
            return new UserApiKeyPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_USER_API_KEY_USER_ID);
    }

    @Override
    public Identity<UserApiKeyRecord, Integer> getIdentity() {
        return (Identity<UserApiKeyRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<UserApiKeyRecord> getPrimaryKey() {
        return Keys.USER_API_KEY__PK_USER_API_KEY;
    }

    @Override
    public List<UniqueKey<UserApiKeyRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.USER_API_KEY__UQ_USER_API_KEY_HASH);
    }

    @Override
    public List<ForeignKey<UserApiKeyRecord, ?>> getReferences() {
        return Arrays.asList(Keys.USER_API_KEY__FK_USER_API_KEY_PK_USER);
    }

    private transient UserPath _user;

    /**
     * Get the implicit join path to the <code>user</code> table.
     */
    public UserPath user() {
        if (_user == null)
            _user = new UserPath(this, Keys.USER_API_KEY__FK_USER_API_KEY_PK_USER, null);

        return _user;
    }

    @Override
    public UserApiKey as(String alias) {
        return new UserApiKey(DSL.name(alias), this);
    }

    @Override
    public UserApiKey as(Name alias) {
        return new UserApiKey(alias, this);
    }

    @Override
    public UserApiKey as(Table<?> alias) {
        return new UserApiKey(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserApiKey rename(String name) {
        return new UserApiKey(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserApiKey rename(Name name) {
        return new UserApiKey(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserApiKey rename(Table<?> name) {
        return new UserApiKey(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserApiKey where(Condition condition) {
        return new UserApiKey(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserApiKey where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserApiKey where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserApiKey where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserApiKey where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserApiKey where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserApiKey where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserApiKey where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserApiKey whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserApiKey whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
