/*
 * This file is generated by jOOQ.
 */
package com.ib.jooq;


import com.ib.jooq.tables.DeckProblems;
import com.ib.jooq.tables.Decks;
import com.ib.jooq.tables.FlashcardReviews;
import com.ib.jooq.tables.Problems;
import com.ib.jooq.tables.ProblemsTopic;
import com.ib.jooq.tables.ReviewLogs;
import com.ib.jooq.tables.ReviewSchedules;
import com.ib.jooq.tables.Solutions;
import com.ib.jooq.tables.Submissions;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in litdeck.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DECK_PROBLEMS_IDX_DECK_PROBLEMS_DECK_ID = Internal.createIndex(DSL.name("idx_deck_problems_deck_id"), DeckProblems.DECK_PROBLEMS, new OrderField[] { DeckProblems.DECK_PROBLEMS.DECK_ID }, false);
    public static final Index DECK_PROBLEMS_IDX_DECK_PROBLEMS_PROBLEM_ID = Internal.createIndex(DSL.name("idx_deck_problems_problem_id"), DeckProblems.DECK_PROBLEMS, new OrderField[] { DeckProblems.DECK_PROBLEMS.PROBLEM_ID }, false);
    public static final Index DECKS_IDX_DECKS_PUBLIC = Internal.createIndex(DSL.name("idx_decks_public"), Decks.DECKS, new OrderField[] { Decks.DECKS.IS_PUBLIC }, false);
    public static final Index DECKS_IDX_DECKS_USER_ID = Internal.createIndex(DSL.name("idx_decks_user_id"), Decks.DECKS, new OrderField[] { Decks.DECKS.USER_ID }, false);
    public static final Index FLASHCARD_REVIEWS_IDX_FLASHCARD_REVIEWS_DECK_ID = Internal.createIndex(DSL.name("idx_flashcard_reviews_deck_id"), FlashcardReviews.FLASHCARD_REVIEWS, new OrderField[] { FlashcardReviews.FLASHCARD_REVIEWS.DECK_ID }, false);
    public static final Index FLASHCARD_REVIEWS_IDX_FLASHCARD_REVIEWS_DUE_DATE = Internal.createIndex(DSL.name("idx_flashcard_reviews_due_date"), FlashcardReviews.FLASHCARD_REVIEWS, new OrderField[] { FlashcardReviews.FLASHCARD_REVIEWS.DUE_DATE }, false);
    public static final Index FLASHCARD_REVIEWS_IDX_FLASHCARD_REVIEWS_USER_DUE = Internal.createIndex(DSL.name("idx_flashcard_reviews_user_due"), FlashcardReviews.FLASHCARD_REVIEWS, new OrderField[] { FlashcardReviews.FLASHCARD_REVIEWS.USER_ID, FlashcardReviews.FLASHCARD_REVIEWS.DUE_DATE }, false);
    public static final Index FLASHCARD_REVIEWS_IDX_FLASHCARD_REVIEWS_USER_ID = Internal.createIndex(DSL.name("idx_flashcard_reviews_user_id"), FlashcardReviews.FLASHCARD_REVIEWS, new OrderField[] { FlashcardReviews.FLASHCARD_REVIEWS.USER_ID }, false);
    public static final Index PROBLEMS_IDX_PROBLEMS_DIFFICULTY = Internal.createIndex(DSL.name("idx_problems_difficulty"), Problems.PROBLEMS, new OrderField[] { Problems.PROBLEMS.DIFFICULTY }, false);
    public static final Index PROBLEMS_IDX_PROBLEMS_FRONTEND_ID = Internal.createIndex(DSL.name("idx_problems_frontend_id"), Problems.PROBLEMS, new OrderField[] { Problems.PROBLEMS.FRONTEND_ID }, false);
    public static final Index PROBLEMS_TOPIC_IDX_PROBLEMS_TOPIC_PROBLEM_ID = Internal.createIndex(DSL.name("idx_problems_topic_problem_id"), ProblemsTopic.PROBLEMS_TOPIC, new OrderField[] { ProblemsTopic.PROBLEMS_TOPIC.PROBLEM_ID }, false);
    public static final Index PROBLEMS_TOPIC_IDX_PROBLEMS_TOPIC_SLUG = Internal.createIndex(DSL.name("idx_problems_topic_slug"), ProblemsTopic.PROBLEMS_TOPIC, new OrderField[] { ProblemsTopic.PROBLEMS_TOPIC.TOPIC_SLUG }, false);
    public static final Index REVIEW_LOGS_IDX_REVIEW_LOGS_PROBLEM_ID = Internal.createIndex(DSL.name("idx_review_logs_problem_id"), ReviewLogs.REVIEW_LOGS, new OrderField[] { ReviewLogs.REVIEW_LOGS.PROBLEM_ID }, false);
    public static final Index REVIEW_LOGS_IDX_REVIEW_LOGS_REVIEW_DATE = Internal.createIndex(DSL.name("idx_review_logs_review_date"), ReviewLogs.REVIEW_LOGS, new OrderField[] { ReviewLogs.REVIEW_LOGS.REVIEW_DATE }, false);
    public static final Index REVIEW_LOGS_IDX_REVIEW_LOGS_USER_ID = Internal.createIndex(DSL.name("idx_review_logs_user_id"), ReviewLogs.REVIEW_LOGS, new OrderField[] { ReviewLogs.REVIEW_LOGS.USER_ID }, false);
    public static final Index REVIEW_SCHEDULES_IDX_REVIEW_SCHEDULES_DUE_DATE = Internal.createIndex(DSL.name("idx_review_schedules_due_date"), ReviewSchedules.REVIEW_SCHEDULES, new OrderField[] { ReviewSchedules.REVIEW_SCHEDULES.DUE_DATE }, false);
    public static final Index REVIEW_SCHEDULES_IDX_REVIEW_SCHEDULES_USER_DUE = Internal.createIndex(DSL.name("idx_review_schedules_user_due"), ReviewSchedules.REVIEW_SCHEDULES, new OrderField[] { ReviewSchedules.REVIEW_SCHEDULES.USER_ID, ReviewSchedules.REVIEW_SCHEDULES.DUE_DATE }, false);
    public static final Index REVIEW_SCHEDULES_IDX_REVIEW_SCHEDULES_USER_ID = Internal.createIndex(DSL.name("idx_review_schedules_user_id"), ReviewSchedules.REVIEW_SCHEDULES, new OrderField[] { ReviewSchedules.REVIEW_SCHEDULES.USER_ID }, false);
    public static final Index SOLUTIONS_IDX_SOLUTIONS_LANGUAGE = Internal.createIndex(DSL.name("idx_solutions_language"), Solutions.SOLUTIONS, new OrderField[] { Solutions.SOLUTIONS.LANGUAGE }, false);
    public static final Index SOLUTIONS_IDX_SOLUTIONS_PROBLEM_ID = Internal.createIndex(DSL.name("idx_solutions_problem_id"), Solutions.SOLUTIONS, new OrderField[] { Solutions.SOLUTIONS.PROBLEM_ID }, false);
    public static final Index SUBMISSIONS_IDX_SUBMISSIONS_USER_TIME = Internal.createIndex(DSL.name("idx_submissions_user_time"), Submissions.SUBMISSIONS, new OrderField[] { Submissions.SUBMISSIONS.USER_ID, Submissions.SUBMISSIONS.SUBMITTED_AT }, false);
}
