/*
 * This file is generated by jOOQ.
 */
package com.ib.jooq;


import com.ib.jooq.tables.DeckProblems;
import com.ib.jooq.tables.Decks;
import com.ib.jooq.tables.FlashcardReviews;
import com.ib.jooq.tables.Problems;
import com.ib.jooq.tables.ProblemsTopic;
import com.ib.jooq.tables.ReviewLogs;
import com.ib.jooq.tables.ReviewSchedules;
import com.ib.jooq.tables.Solutions;
import com.ib.jooq.tables.Submissions;
import com.ib.jooq.tables.Topics;
import com.ib.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Litdeck extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>litdeck</code>
     */
    public static final Litdeck LITDECK = new Litdeck();

    /**
     * The table <code>litdeck.deck_problems</code>.
     */
    public final DeckProblems DECK_PROBLEMS = DeckProblems.DECK_PROBLEMS;

    /**
     * The table <code>litdeck.decks</code>.
     */
    public final Decks DECKS = Decks.DECKS;

    /**
     * The table <code>litdeck.flashcard_reviews</code>.
     */
    public final FlashcardReviews FLASHCARD_REVIEWS = FlashcardReviews.FLASHCARD_REVIEWS;

    /**
     * The table <code>litdeck.problems</code>.
     */
    public final Problems PROBLEMS = Problems.PROBLEMS;

    /**
     * The table <code>litdeck.problems_topic</code>.
     */
    public final ProblemsTopic PROBLEMS_TOPIC = ProblemsTopic.PROBLEMS_TOPIC;

    /**
     * The table <code>litdeck.review_logs</code>.
     */
    public final ReviewLogs REVIEW_LOGS = ReviewLogs.REVIEW_LOGS;

    /**
     * The table <code>litdeck.review_schedules</code>.
     */
    public final ReviewSchedules REVIEW_SCHEDULES = ReviewSchedules.REVIEW_SCHEDULES;

    /**
     * The table <code>litdeck.solutions</code>.
     */
    public final Solutions SOLUTIONS = Solutions.SOLUTIONS;

    /**
     * The table <code>litdeck.submissions</code>.
     */
    public final Submissions SUBMISSIONS = Submissions.SUBMISSIONS;

    /**
     * The table <code>litdeck.topics</code>.
     */
    public final Topics TOPICS = Topics.TOPICS;

    /**
     * The table <code>litdeck.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Litdeck() {
        super(DSL.name("litdeck"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            DeckProblems.DECK_PROBLEMS,
            Decks.DECKS,
            FlashcardReviews.FLASHCARD_REVIEWS,
            Problems.PROBLEMS,
            ProblemsTopic.PROBLEMS_TOPIC,
            ReviewLogs.REVIEW_LOGS,
            ReviewSchedules.REVIEW_SCHEDULES,
            Solutions.SOLUTIONS,
            Submissions.SUBMISSIONS,
            Topics.TOPICS,
            Users.USERS
        );
    }
}
