/*
 * This file is generated by jOOQ.
 */
package com.litdeck.backend.jooq.tables.pojos;


import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReviewSchedulespojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String userId;
    private Integer problemId;
    private LocalDateTime dueDate;
    private Double stability;
    private Double difficulty;
    private Integer elapsedDays;
    private Integer scheduledDays;
    private Integer reps;
    private Integer lapses;
    private String state;
    private LocalDateTime lastReview;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public ReviewSchedulespojo() {}

    public ReviewSchedulespojo(ReviewSchedulespojo value) {
        this.id = value.id;
        this.userId = value.userId;
        this.problemId = value.problemId;
        this.dueDate = value.dueDate;
        this.stability = value.stability;
        this.difficulty = value.difficulty;
        this.elapsedDays = value.elapsedDays;
        this.scheduledDays = value.scheduledDays;
        this.reps = value.reps;
        this.lapses = value.lapses;
        this.state = value.state;
        this.lastReview = value.lastReview;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public ReviewSchedulespojo(
        Integer id,
        String userId,
        Integer problemId,
        LocalDateTime dueDate,
        Double stability,
        Double difficulty,
        Integer elapsedDays,
        Integer scheduledDays,
        Integer reps,
        Integer lapses,
        String state,
        LocalDateTime lastReview,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.userId = userId;
        this.problemId = problemId;
        this.dueDate = dueDate;
        this.stability = stability;
        this.difficulty = difficulty;
        this.elapsedDays = elapsedDays;
        this.scheduledDays = scheduledDays;
        this.reps = reps;
        this.lapses = lapses;
        this.state = state;
        this.lastReview = lastReview;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>litdeck.review_schedules.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>litdeck.review_schedules.id</code>.
     */
    public ReviewSchedulespojo setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.user_id</code>.
     */
    @NotNull
    @Size(max = 36)
    public String getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>litdeck.review_schedules.user_id</code>.
     */
    public ReviewSchedulespojo setUserId(String userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.problem_id</code>.
     */
    @NotNull
    public Integer getProblemId() {
        return this.problemId;
    }

    /**
     * Setter for <code>litdeck.review_schedules.problem_id</code>.
     */
    public ReviewSchedulespojo setProblemId(Integer problemId) {
        this.problemId = problemId;
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.due_date</code>.
     */
    @NotNull
    public LocalDateTime getDueDate() {
        return this.dueDate;
    }

    /**
     * Setter for <code>litdeck.review_schedules.due_date</code>.
     */
    public ReviewSchedulespojo setDueDate(LocalDateTime dueDate) {
        this.dueDate = dueDate;
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.stability</code>.
     */
    public Double getStability() {
        return this.stability;
    }

    /**
     * Setter for <code>litdeck.review_schedules.stability</code>.
     */
    public ReviewSchedulespojo setStability(Double stability) {
        this.stability = stability;
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.difficulty</code>.
     */
    public Double getDifficulty() {
        return this.difficulty;
    }

    /**
     * Setter for <code>litdeck.review_schedules.difficulty</code>.
     */
    public ReviewSchedulespojo setDifficulty(Double difficulty) {
        this.difficulty = difficulty;
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.elapsed_days</code>.
     */
    public Integer getElapsedDays() {
        return this.elapsedDays;
    }

    /**
     * Setter for <code>litdeck.review_schedules.elapsed_days</code>.
     */
    public ReviewSchedulespojo setElapsedDays(Integer elapsedDays) {
        this.elapsedDays = elapsedDays;
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.scheduled_days</code>.
     */
    public Integer getScheduledDays() {
        return this.scheduledDays;
    }

    /**
     * Setter for <code>litdeck.review_schedules.scheduled_days</code>.
     */
    public ReviewSchedulespojo setScheduledDays(Integer scheduledDays) {
        this.scheduledDays = scheduledDays;
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.reps</code>.
     */
    public Integer getReps() {
        return this.reps;
    }

    /**
     * Setter for <code>litdeck.review_schedules.reps</code>.
     */
    public ReviewSchedulespojo setReps(Integer reps) {
        this.reps = reps;
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.lapses</code>.
     */
    public Integer getLapses() {
        return this.lapses;
    }

    /**
     * Setter for <code>litdeck.review_schedules.lapses</code>.
     */
    public ReviewSchedulespojo setLapses(Integer lapses) {
        this.lapses = lapses;
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.state</code>.
     */
    @Size(max = 50)
    public String getState() {
        return this.state;
    }

    /**
     * Setter for <code>litdeck.review_schedules.state</code>.
     */
    public ReviewSchedulespojo setState(String state) {
        this.state = state;
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.last_review</code>.
     */
    public LocalDateTime getLastReview() {
        return this.lastReview;
    }

    /**
     * Setter for <code>litdeck.review_schedules.last_review</code>.
     */
    public ReviewSchedulespojo setLastReview(LocalDateTime lastReview) {
        this.lastReview = lastReview;
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>litdeck.review_schedules.created_at</code>.
     */
    public ReviewSchedulespojo setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>litdeck.review_schedules.updated_at</code>.
     */
    public ReviewSchedulespojo setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ReviewSchedulespojo other = (ReviewSchedulespojo) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.problemId == null) {
            if (other.problemId != null)
                return false;
        }
        else if (!this.problemId.equals(other.problemId))
            return false;
        if (this.dueDate == null) {
            if (other.dueDate != null)
                return false;
        }
        else if (!this.dueDate.equals(other.dueDate))
            return false;
        if (this.stability == null) {
            if (other.stability != null)
                return false;
        }
        else if (!this.stability.equals(other.stability))
            return false;
        if (this.difficulty == null) {
            if (other.difficulty != null)
                return false;
        }
        else if (!this.difficulty.equals(other.difficulty))
            return false;
        if (this.elapsedDays == null) {
            if (other.elapsedDays != null)
                return false;
        }
        else if (!this.elapsedDays.equals(other.elapsedDays))
            return false;
        if (this.scheduledDays == null) {
            if (other.scheduledDays != null)
                return false;
        }
        else if (!this.scheduledDays.equals(other.scheduledDays))
            return false;
        if (this.reps == null) {
            if (other.reps != null)
                return false;
        }
        else if (!this.reps.equals(other.reps))
            return false;
        if (this.lapses == null) {
            if (other.lapses != null)
                return false;
        }
        else if (!this.lapses.equals(other.lapses))
            return false;
        if (this.state == null) {
            if (other.state != null)
                return false;
        }
        else if (!this.state.equals(other.state))
            return false;
        if (this.lastReview == null) {
            if (other.lastReview != null)
                return false;
        }
        else if (!this.lastReview.equals(other.lastReview))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.problemId == null) ? 0 : this.problemId.hashCode());
        result = prime * result + ((this.dueDate == null) ? 0 : this.dueDate.hashCode());
        result = prime * result + ((this.stability == null) ? 0 : this.stability.hashCode());
        result = prime * result + ((this.difficulty == null) ? 0 : this.difficulty.hashCode());
        result = prime * result + ((this.elapsedDays == null) ? 0 : this.elapsedDays.hashCode());
        result = prime * result + ((this.scheduledDays == null) ? 0 : this.scheduledDays.hashCode());
        result = prime * result + ((this.reps == null) ? 0 : this.reps.hashCode());
        result = prime * result + ((this.lapses == null) ? 0 : this.lapses.hashCode());
        result = prime * result + ((this.state == null) ? 0 : this.state.hashCode());
        result = prime * result + ((this.lastReview == null) ? 0 : this.lastReview.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ReviewSchedulespojo (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(problemId);
        sb.append(", ").append(dueDate);
        sb.append(", ").append(stability);
        sb.append(", ").append(difficulty);
        sb.append(", ").append(elapsedDays);
        sb.append(", ").append(scheduledDays);
        sb.append(", ").append(reps);
        sb.append(", ").append(lapses);
        sb.append(", ").append(state);
        sb.append(", ").append(lastReview);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
