/*
 * This file is generated by jOOQ.
 */
package com.litdeck.backend.jooq.tables.pojos;


import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReviewLogspojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String userId;
    private Integer problemId;
    private Integer rating;
    private String state;
    private LocalDateTime dueDate;
    private Double stability;
    private Double difficulty;
    private Integer elapsedDays;
    private Integer lastElapsedDays;
    private Integer scheduledDays;
    private LocalDateTime reviewDate;
    private LocalDateTime createdAt;

    public ReviewLogspojo() {}

    public ReviewLogspojo(ReviewLogspojo value) {
        this.id = value.id;
        this.userId = value.userId;
        this.problemId = value.problemId;
        this.rating = value.rating;
        this.state = value.state;
        this.dueDate = value.dueDate;
        this.stability = value.stability;
        this.difficulty = value.difficulty;
        this.elapsedDays = value.elapsedDays;
        this.lastElapsedDays = value.lastElapsedDays;
        this.scheduledDays = value.scheduledDays;
        this.reviewDate = value.reviewDate;
        this.createdAt = value.createdAt;
    }

    public ReviewLogspojo(
        Integer id,
        String userId,
        Integer problemId,
        Integer rating,
        String state,
        LocalDateTime dueDate,
        Double stability,
        Double difficulty,
        Integer elapsedDays,
        Integer lastElapsedDays,
        Integer scheduledDays,
        LocalDateTime reviewDate,
        LocalDateTime createdAt
    ) {
        this.id = id;
        this.userId = userId;
        this.problemId = problemId;
        this.rating = rating;
        this.state = state;
        this.dueDate = dueDate;
        this.stability = stability;
        this.difficulty = difficulty;
        this.elapsedDays = elapsedDays;
        this.lastElapsedDays = lastElapsedDays;
        this.scheduledDays = scheduledDays;
        this.reviewDate = reviewDate;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>litdeck.review_logs.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>litdeck.review_logs.id</code>.
     */
    public ReviewLogspojo setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>litdeck.review_logs.user_id</code>.
     */
    @NotNull
    @Size(max = 36)
    public String getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>litdeck.review_logs.user_id</code>.
     */
    public ReviewLogspojo setUserId(String userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>litdeck.review_logs.problem_id</code>.
     */
    @NotNull
    public Integer getProblemId() {
        return this.problemId;
    }

    /**
     * Setter for <code>litdeck.review_logs.problem_id</code>.
     */
    public ReviewLogspojo setProblemId(Integer problemId) {
        this.problemId = problemId;
        return this;
    }

    /**
     * Getter for <code>litdeck.review_logs.rating</code>.
     */
    @NotNull
    public Integer getRating() {
        return this.rating;
    }

    /**
     * Setter for <code>litdeck.review_logs.rating</code>.
     */
    public ReviewLogspojo setRating(Integer rating) {
        this.rating = rating;
        return this;
    }

    /**
     * Getter for <code>litdeck.review_logs.state</code>.
     */
    @NotNull
    @Size(max = 50)
    public String getState() {
        return this.state;
    }

    /**
     * Setter for <code>litdeck.review_logs.state</code>.
     */
    public ReviewLogspojo setState(String state) {
        this.state = state;
        return this;
    }

    /**
     * Getter for <code>litdeck.review_logs.due_date</code>.
     */
    @NotNull
    public LocalDateTime getDueDate() {
        return this.dueDate;
    }

    /**
     * Setter for <code>litdeck.review_logs.due_date</code>.
     */
    public ReviewLogspojo setDueDate(LocalDateTime dueDate) {
        this.dueDate = dueDate;
        return this;
    }

    /**
     * Getter for <code>litdeck.review_logs.stability</code>.
     */
    @NotNull
    public Double getStability() {
        return this.stability;
    }

    /**
     * Setter for <code>litdeck.review_logs.stability</code>.
     */
    public ReviewLogspojo setStability(Double stability) {
        this.stability = stability;
        return this;
    }

    /**
     * Getter for <code>litdeck.review_logs.difficulty</code>.
     */
    @NotNull
    public Double getDifficulty() {
        return this.difficulty;
    }

    /**
     * Setter for <code>litdeck.review_logs.difficulty</code>.
     */
    public ReviewLogspojo setDifficulty(Double difficulty) {
        this.difficulty = difficulty;
        return this;
    }

    /**
     * Getter for <code>litdeck.review_logs.elapsed_days</code>.
     */
    @NotNull
    public Integer getElapsedDays() {
        return this.elapsedDays;
    }

    /**
     * Setter for <code>litdeck.review_logs.elapsed_days</code>.
     */
    public ReviewLogspojo setElapsedDays(Integer elapsedDays) {
        this.elapsedDays = elapsedDays;
        return this;
    }

    /**
     * Getter for <code>litdeck.review_logs.last_elapsed_days</code>.
     */
    @NotNull
    public Integer getLastElapsedDays() {
        return this.lastElapsedDays;
    }

    /**
     * Setter for <code>litdeck.review_logs.last_elapsed_days</code>.
     */
    public ReviewLogspojo setLastElapsedDays(Integer lastElapsedDays) {
        this.lastElapsedDays = lastElapsedDays;
        return this;
    }

    /**
     * Getter for <code>litdeck.review_logs.scheduled_days</code>.
     */
    @NotNull
    public Integer getScheduledDays() {
        return this.scheduledDays;
    }

    /**
     * Setter for <code>litdeck.review_logs.scheduled_days</code>.
     */
    public ReviewLogspojo setScheduledDays(Integer scheduledDays) {
        this.scheduledDays = scheduledDays;
        return this;
    }

    /**
     * Getter for <code>litdeck.review_logs.review_date</code>.
     */
    @NotNull
    public LocalDateTime getReviewDate() {
        return this.reviewDate;
    }

    /**
     * Setter for <code>litdeck.review_logs.review_date</code>.
     */
    public ReviewLogspojo setReviewDate(LocalDateTime reviewDate) {
        this.reviewDate = reviewDate;
        return this;
    }

    /**
     * Getter for <code>litdeck.review_logs.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>litdeck.review_logs.created_at</code>.
     */
    public ReviewLogspojo setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ReviewLogspojo other = (ReviewLogspojo) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.problemId == null) {
            if (other.problemId != null)
                return false;
        }
        else if (!this.problemId.equals(other.problemId))
            return false;
        if (this.rating == null) {
            if (other.rating != null)
                return false;
        }
        else if (!this.rating.equals(other.rating))
            return false;
        if (this.state == null) {
            if (other.state != null)
                return false;
        }
        else if (!this.state.equals(other.state))
            return false;
        if (this.dueDate == null) {
            if (other.dueDate != null)
                return false;
        }
        else if (!this.dueDate.equals(other.dueDate))
            return false;
        if (this.stability == null) {
            if (other.stability != null)
                return false;
        }
        else if (!this.stability.equals(other.stability))
            return false;
        if (this.difficulty == null) {
            if (other.difficulty != null)
                return false;
        }
        else if (!this.difficulty.equals(other.difficulty))
            return false;
        if (this.elapsedDays == null) {
            if (other.elapsedDays != null)
                return false;
        }
        else if (!this.elapsedDays.equals(other.elapsedDays))
            return false;
        if (this.lastElapsedDays == null) {
            if (other.lastElapsedDays != null)
                return false;
        }
        else if (!this.lastElapsedDays.equals(other.lastElapsedDays))
            return false;
        if (this.scheduledDays == null) {
            if (other.scheduledDays != null)
                return false;
        }
        else if (!this.scheduledDays.equals(other.scheduledDays))
            return false;
        if (this.reviewDate == null) {
            if (other.reviewDate != null)
                return false;
        }
        else if (!this.reviewDate.equals(other.reviewDate))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.problemId == null) ? 0 : this.problemId.hashCode());
        result = prime * result + ((this.rating == null) ? 0 : this.rating.hashCode());
        result = prime * result + ((this.state == null) ? 0 : this.state.hashCode());
        result = prime * result + ((this.dueDate == null) ? 0 : this.dueDate.hashCode());
        result = prime * result + ((this.stability == null) ? 0 : this.stability.hashCode());
        result = prime * result + ((this.difficulty == null) ? 0 : this.difficulty.hashCode());
        result = prime * result + ((this.elapsedDays == null) ? 0 : this.elapsedDays.hashCode());
        result = prime * result + ((this.lastElapsedDays == null) ? 0 : this.lastElapsedDays.hashCode());
        result = prime * result + ((this.scheduledDays == null) ? 0 : this.scheduledDays.hashCode());
        result = prime * result + ((this.reviewDate == null) ? 0 : this.reviewDate.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ReviewLogspojo (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(problemId);
        sb.append(", ").append(rating);
        sb.append(", ").append(state);
        sb.append(", ").append(dueDate);
        sb.append(", ").append(stability);
        sb.append(", ").append(difficulty);
        sb.append(", ").append(elapsedDays);
        sb.append(", ").append(lastElapsedDays);
        sb.append(", ").append(scheduledDays);
        sb.append(", ").append(reviewDate);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
