/*
 * This file is generated by jOOQ.
 */
package com.litdeck.backend.jooq.tables.pojos;


import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Solutionspojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer problemId;
    private String title;
    private String language;
    private String code;
    private String explanation;
    private String timeComplexity;
    private String spaceComplexity;
    private Byte isOptimal;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public Solutionspojo() {}

    public Solutionspojo(Solutionspojo value) {
        this.id = value.id;
        this.problemId = value.problemId;
        this.title = value.title;
        this.language = value.language;
        this.code = value.code;
        this.explanation = value.explanation;
        this.timeComplexity = value.timeComplexity;
        this.spaceComplexity = value.spaceComplexity;
        this.isOptimal = value.isOptimal;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Solutionspojo(
        Integer id,
        Integer problemId,
        String title,
        String language,
        String code,
        String explanation,
        String timeComplexity,
        String spaceComplexity,
        Byte isOptimal,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.problemId = problemId;
        this.title = title;
        this.language = language;
        this.code = code;
        this.explanation = explanation;
        this.timeComplexity = timeComplexity;
        this.spaceComplexity = spaceComplexity;
        this.isOptimal = isOptimal;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>litdeck.solutions.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>litdeck.solutions.id</code>.
     */
    public Solutionspojo setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>litdeck.solutions.problem_id</code>.
     */
    @NotNull
    public Integer getProblemId() {
        return this.problemId;
    }

    /**
     * Setter for <code>litdeck.solutions.problem_id</code>.
     */
    public Solutionspojo setProblemId(Integer problemId) {
        this.problemId = problemId;
        return this;
    }

    /**
     * Getter for <code>litdeck.solutions.title</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>litdeck.solutions.title</code>.
     */
    public Solutionspojo setTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * Getter for <code>litdeck.solutions.language</code>.
     */
    @NotNull
    @Size(max = 50)
    public String getLanguage() {
        return this.language;
    }

    /**
     * Setter for <code>litdeck.solutions.language</code>.
     */
    public Solutionspojo setLanguage(String language) {
        this.language = language;
        return this;
    }

    /**
     * Getter for <code>litdeck.solutions.code</code>.
     */
    @NotNull
    @Size(max = 65535)
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for <code>litdeck.solutions.code</code>.
     */
    public Solutionspojo setCode(String code) {
        this.code = code;
        return this;
    }

    /**
     * Getter for <code>litdeck.solutions.explanation</code>.
     */
    @Size(max = 65535)
    public String getExplanation() {
        return this.explanation;
    }

    /**
     * Setter for <code>litdeck.solutions.explanation</code>.
     */
    public Solutionspojo setExplanation(String explanation) {
        this.explanation = explanation;
        return this;
    }

    /**
     * Getter for <code>litdeck.solutions.time_complexity</code>.
     */
    @Size(max = 100)
    public String getTimeComplexity() {
        return this.timeComplexity;
    }

    /**
     * Setter for <code>litdeck.solutions.time_complexity</code>.
     */
    public Solutionspojo setTimeComplexity(String timeComplexity) {
        this.timeComplexity = timeComplexity;
        return this;
    }

    /**
     * Getter for <code>litdeck.solutions.space_complexity</code>.
     */
    @Size(max = 100)
    public String getSpaceComplexity() {
        return this.spaceComplexity;
    }

    /**
     * Setter for <code>litdeck.solutions.space_complexity</code>.
     */
    public Solutionspojo setSpaceComplexity(String spaceComplexity) {
        this.spaceComplexity = spaceComplexity;
        return this;
    }

    /**
     * Getter for <code>litdeck.solutions.is_optimal</code>.
     */
    public Byte getIsOptimal() {
        return this.isOptimal;
    }

    /**
     * Setter for <code>litdeck.solutions.is_optimal</code>.
     */
    public Solutionspojo setIsOptimal(Byte isOptimal) {
        this.isOptimal = isOptimal;
        return this;
    }

    /**
     * Getter for <code>litdeck.solutions.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>litdeck.solutions.created_at</code>.
     */
    public Solutionspojo setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>litdeck.solutions.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>litdeck.solutions.updated_at</code>.
     */
    public Solutionspojo setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Solutionspojo other = (Solutionspojo) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.problemId == null) {
            if (other.problemId != null)
                return false;
        }
        else if (!this.problemId.equals(other.problemId))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.language == null) {
            if (other.language != null)
                return false;
        }
        else if (!this.language.equals(other.language))
            return false;
        if (this.code == null) {
            if (other.code != null)
                return false;
        }
        else if (!this.code.equals(other.code))
            return false;
        if (this.explanation == null) {
            if (other.explanation != null)
                return false;
        }
        else if (!this.explanation.equals(other.explanation))
            return false;
        if (this.timeComplexity == null) {
            if (other.timeComplexity != null)
                return false;
        }
        else if (!this.timeComplexity.equals(other.timeComplexity))
            return false;
        if (this.spaceComplexity == null) {
            if (other.spaceComplexity != null)
                return false;
        }
        else if (!this.spaceComplexity.equals(other.spaceComplexity))
            return false;
        if (this.isOptimal == null) {
            if (other.isOptimal != null)
                return false;
        }
        else if (!this.isOptimal.equals(other.isOptimal))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.problemId == null) ? 0 : this.problemId.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.language == null) ? 0 : this.language.hashCode());
        result = prime * result + ((this.code == null) ? 0 : this.code.hashCode());
        result = prime * result + ((this.explanation == null) ? 0 : this.explanation.hashCode());
        result = prime * result + ((this.timeComplexity == null) ? 0 : this.timeComplexity.hashCode());
        result = prime * result + ((this.spaceComplexity == null) ? 0 : this.spaceComplexity.hashCode());
        result = prime * result + ((this.isOptimal == null) ? 0 : this.isOptimal.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Solutionspojo (");

        sb.append(id);
        sb.append(", ").append(problemId);
        sb.append(", ").append(title);
        sb.append(", ").append(language);
        sb.append(", ").append(code);
        sb.append(", ").append(explanation);
        sb.append(", ").append(timeComplexity);
        sb.append(", ").append(spaceComplexity);
        sb.append(", ").append(isOptimal);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
