/*
 * This file is generated by jOOQ.
 */
package com.litdeck.backend.jooq.tables.pojos;


import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Submissionspojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String title;
    private String titleSlug;
    private LocalDateTime submittedAt;
    private LocalDateTime createdAt;
    private String userId;

    public Submissionspojo() {}

    public Submissionspojo(Submissionspojo value) {
        this.id = value.id;
        this.title = value.title;
        this.titleSlug = value.titleSlug;
        this.submittedAt = value.submittedAt;
        this.createdAt = value.createdAt;
        this.userId = value.userId;
    }

    public Submissionspojo(
        String id,
        String title,
        String titleSlug,
        LocalDateTime submittedAt,
        LocalDateTime createdAt,
        String userId
    ) {
        this.id = id;
        this.title = title;
        this.titleSlug = titleSlug;
        this.submittedAt = submittedAt;
        this.createdAt = createdAt;
        this.userId = userId;
    }

    /**
     * Getter for <code>litdeck.submissions.id</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>litdeck.submissions.id</code>.
     */
    public Submissionspojo setId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>litdeck.submissions.title</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>litdeck.submissions.title</code>.
     */
    public Submissionspojo setTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * Getter for <code>litdeck.submissions.title_slug</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getTitleSlug() {
        return this.titleSlug;
    }

    /**
     * Setter for <code>litdeck.submissions.title_slug</code>.
     */
    public Submissionspojo setTitleSlug(String titleSlug) {
        this.titleSlug = titleSlug;
        return this;
    }

    /**
     * Getter for <code>litdeck.submissions.submitted_at</code>.
     */
    @NotNull
    public LocalDateTime getSubmittedAt() {
        return this.submittedAt;
    }

    /**
     * Setter for <code>litdeck.submissions.submitted_at</code>.
     */
    public Submissionspojo setSubmittedAt(LocalDateTime submittedAt) {
        this.submittedAt = submittedAt;
        return this;
    }

    /**
     * Getter for <code>litdeck.submissions.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>litdeck.submissions.created_at</code>.
     */
    public Submissionspojo setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>litdeck.submissions.user_id</code>.
     */
    @NotNull
    @Size(max = 36)
    public String getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>litdeck.submissions.user_id</code>.
     */
    public Submissionspojo setUserId(String userId) {
        this.userId = userId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Submissionspojo other = (Submissionspojo) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.titleSlug == null) {
            if (other.titleSlug != null)
                return false;
        }
        else if (!this.titleSlug.equals(other.titleSlug))
            return false;
        if (this.submittedAt == null) {
            if (other.submittedAt != null)
                return false;
        }
        else if (!this.submittedAt.equals(other.submittedAt))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.titleSlug == null) ? 0 : this.titleSlug.hashCode());
        result = prime * result + ((this.submittedAt == null) ? 0 : this.submittedAt.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Submissionspojo (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(titleSlug);
        sb.append(", ").append(submittedAt);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
