/*
 * This file is generated by jOOQ.
 */
package com.litdeck.backend.jooq.tables.pojos;


import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Userspojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String email;
    private String username;
    private LocalDateTime createdAt;
    private String leetcodeUsername;

    public Userspojo() {}

    public Userspojo(Userspojo value) {
        this.id = value.id;
        this.email = value.email;
        this.username = value.username;
        this.createdAt = value.createdAt;
        this.leetcodeUsername = value.leetcodeUsername;
    }

    public Userspojo(
        String id,
        String email,
        String username,
        LocalDateTime createdAt,
        String leetcodeUsername
    ) {
        this.id = id;
        this.email = email;
        this.username = username;
        this.createdAt = createdAt;
        this.leetcodeUsername = leetcodeUsername;
    }

    /**
     * Getter for <code>litdeck.users.id</code>.
     */
    @Size(max = 36)
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>litdeck.users.id</code>.
     */
    public Userspojo setId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>litdeck.users.email</code>.
     */
    @Size(max = 255)
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>litdeck.users.email</code>.
     */
    public Userspojo setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>litdeck.users.username</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>litdeck.users.username</code>.
     */
    public Userspojo setUsername(String username) {
        this.username = username;
        return this;
    }

    /**
     * Getter for <code>litdeck.users.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>litdeck.users.created_at</code>.
     */
    public Userspojo setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>litdeck.users.leetcode_username</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getLeetcodeUsername() {
        return this.leetcodeUsername;
    }

    /**
     * Setter for <code>litdeck.users.leetcode_username</code>.
     */
    public Userspojo setLeetcodeUsername(String leetcodeUsername) {
        this.leetcodeUsername = leetcodeUsername;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Userspojo other = (Userspojo) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.username == null) {
            if (other.username != null)
                return false;
        }
        else if (!this.username.equals(other.username))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.leetcodeUsername == null) {
            if (other.leetcodeUsername != null)
                return false;
        }
        else if (!this.leetcodeUsername.equals(other.leetcodeUsername))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.leetcodeUsername == null) ? 0 : this.leetcodeUsername.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Userspojo (");

        sb.append(id);
        sb.append(", ").append(email);
        sb.append(", ").append(username);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(leetcodeUsername);

        sb.append(")");
        return sb.toString();
    }
}
