/*
 * This file is generated by jOOQ.
 */
package com.ib.jooq.tables.pojos;


import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Deckspojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String userId;
    private String name;
    private String description;
    private Byte isPublic;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public Deckspojo() {}

    public Deckspojo(Deckspojo value) {
        this.id = value.id;
        this.userId = value.userId;
        this.name = value.name;
        this.description = value.description;
        this.isPublic = value.isPublic;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Deckspojo(
        Integer id,
        String userId,
        String name,
        String description,
        Byte isPublic,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.userId = userId;
        this.name = name;
        this.description = description;
        this.isPublic = isPublic;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>litdeck.decks.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>litdeck.decks.id</code>.
     */
    public Deckspojo setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>litdeck.decks.user_id</code>.
     */
    @NotNull
    @Size(max = 36)
    public String getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>litdeck.decks.user_id</code>.
     */
    public Deckspojo setUserId(String userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>litdeck.decks.name</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>litdeck.decks.name</code>.
     */
    public Deckspojo setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>litdeck.decks.description</code>.
     */
    @Size(max = 65535)
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>litdeck.decks.description</code>.
     */
    public Deckspojo setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Getter for <code>litdeck.decks.is_public</code>.
     */
    public Byte getIsPublic() {
        return this.isPublic;
    }

    /**
     * Setter for <code>litdeck.decks.is_public</code>.
     */
    public Deckspojo setIsPublic(Byte isPublic) {
        this.isPublic = isPublic;
        return this;
    }

    /**
     * Getter for <code>litdeck.decks.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>litdeck.decks.created_at</code>.
     */
    public Deckspojo setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>litdeck.decks.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>litdeck.decks.updated_at</code>.
     */
    public Deckspojo setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Deckspojo other = (Deckspojo) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.isPublic == null) {
            if (other.isPublic != null)
                return false;
        }
        else if (!this.isPublic.equals(other.isPublic))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.isPublic == null) ? 0 : this.isPublic.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Deckspojo (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(isPublic);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
