/*
 * This file is generated by jOOQ.
 */
package com.ib.jooq.tables.pojos;


import jakarta.validation.constraints.NotNull;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DeckProblemspojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer deckId;
    private Integer problemId;
    private LocalDateTime addedAt;

    public DeckProblemspojo() {}

    public DeckProblemspojo(DeckProblemspojo value) {
        this.deckId = value.deckId;
        this.problemId = value.problemId;
        this.addedAt = value.addedAt;
    }

    public DeckProblemspojo(
        Integer deckId,
        Integer problemId,
        LocalDateTime addedAt
    ) {
        this.deckId = deckId;
        this.problemId = problemId;
        this.addedAt = addedAt;
    }

    /**
     * Getter for <code>litdeck.deck_problems.deck_id</code>.
     */
    @NotNull
    public Integer getDeckId() {
        return this.deckId;
    }

    /**
     * Setter for <code>litdeck.deck_problems.deck_id</code>.
     */
    public DeckProblemspojo setDeckId(Integer deckId) {
        this.deckId = deckId;
        return this;
    }

    /**
     * Getter for <code>litdeck.deck_problems.problem_id</code>.
     */
    @NotNull
    public Integer getProblemId() {
        return this.problemId;
    }

    /**
     * Setter for <code>litdeck.deck_problems.problem_id</code>.
     */
    public DeckProblemspojo setProblemId(Integer problemId) {
        this.problemId = problemId;
        return this;
    }

    /**
     * Getter for <code>litdeck.deck_problems.added_at</code>.
     */
    public LocalDateTime getAddedAt() {
        return this.addedAt;
    }

    /**
     * Setter for <code>litdeck.deck_problems.added_at</code>.
     */
    public DeckProblemspojo setAddedAt(LocalDateTime addedAt) {
        this.addedAt = addedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final DeckProblemspojo other = (DeckProblemspojo) obj;
        if (this.deckId == null) {
            if (other.deckId != null)
                return false;
        }
        else if (!this.deckId.equals(other.deckId))
            return false;
        if (this.problemId == null) {
            if (other.problemId != null)
                return false;
        }
        else if (!this.problemId.equals(other.problemId))
            return false;
        if (this.addedAt == null) {
            if (other.addedAt != null)
                return false;
        }
        else if (!this.addedAt.equals(other.addedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.deckId == null) ? 0 : this.deckId.hashCode());
        result = prime * result + ((this.problemId == null) ? 0 : this.problemId.hashCode());
        result = prime * result + ((this.addedAt == null) ? 0 : this.addedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DeckProblemspojo (");

        sb.append(deckId);
        sb.append(", ").append(problemId);
        sb.append(", ").append(addedAt);

        sb.append(")");
        return sb.toString();
    }
}
