/*
 * This file is generated by jOOQ.
 */
package com.ib.jooq.tables.pojos;


import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProblemsTopicpojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer problemId;
    private String topicSlug;

    public ProblemsTopicpojo() {}

    public ProblemsTopicpojo(ProblemsTopicpojo value) {
        this.problemId = value.problemId;
        this.topicSlug = value.topicSlug;
    }

    public ProblemsTopicpojo(
        Integer problemId,
        String topicSlug
    ) {
        this.problemId = problemId;
        this.topicSlug = topicSlug;
    }

    /**
     * Getter for <code>litdeck.problems_topic.problem_id</code>.
     */
    @NotNull
    public Integer getProblemId() {
        return this.problemId;
    }

    /**
     * Setter for <code>litdeck.problems_topic.problem_id</code>.
     */
    public ProblemsTopicpojo setProblemId(Integer problemId) {
        this.problemId = problemId;
        return this;
    }

    /**
     * Getter for <code>litdeck.problems_topic.topic_slug</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getTopicSlug() {
        return this.topicSlug;
    }

    /**
     * Setter for <code>litdeck.problems_topic.topic_slug</code>.
     */
    public ProblemsTopicpojo setTopicSlug(String topicSlug) {
        this.topicSlug = topicSlug;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ProblemsTopicpojo other = (ProblemsTopicpojo) obj;
        if (this.problemId == null) {
            if (other.problemId != null)
                return false;
        }
        else if (!this.problemId.equals(other.problemId))
            return false;
        if (this.topicSlug == null) {
            if (other.topicSlug != null)
                return false;
        }
        else if (!this.topicSlug.equals(other.topicSlug))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.problemId == null) ? 0 : this.problemId.hashCode());
        result = prime * result + ((this.topicSlug == null) ? 0 : this.topicSlug.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProblemsTopicpojo (");

        sb.append(problemId);
        sb.append(", ").append(topicSlug);

        sb.append(")");
        return sb.toString();
    }
}
