/*
 * This file is generated by jOOQ.
 */
package com.ib.jooq.tables.pojos;


import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.JSON;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Problemspojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer frontendId;
    private String title;
    private String titleSlug;
    private String difficulty;
    private Byte isPaidOnly;
    private String content;
    private JSON topicTags;
    private String exampleTestcases;
    private JSON similarQuestions;
    private LocalDateTime createdAt;

    public Problemspojo() {}

    public Problemspojo(Problemspojo value) {
        this.id = value.id;
        this.frontendId = value.frontendId;
        this.title = value.title;
        this.titleSlug = value.titleSlug;
        this.difficulty = value.difficulty;
        this.isPaidOnly = value.isPaidOnly;
        this.content = value.content;
        this.topicTags = value.topicTags;
        this.exampleTestcases = value.exampleTestcases;
        this.similarQuestions = value.similarQuestions;
        this.createdAt = value.createdAt;
    }

    public Problemspojo(
        Integer id,
        Integer frontendId,
        String title,
        String titleSlug,
        String difficulty,
        Byte isPaidOnly,
        String content,
        JSON topicTags,
        String exampleTestcases,
        JSON similarQuestions,
        LocalDateTime createdAt
    ) {
        this.id = id;
        this.frontendId = frontendId;
        this.title = title;
        this.titleSlug = titleSlug;
        this.difficulty = difficulty;
        this.isPaidOnly = isPaidOnly;
        this.content = content;
        this.topicTags = topicTags;
        this.exampleTestcases = exampleTestcases;
        this.similarQuestions = similarQuestions;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>litdeck.problems.id</code>.
     */
    @NotNull
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>litdeck.problems.id</code>.
     */
    public Problemspojo setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>litdeck.problems.frontend_id</code>.
     */
    @NotNull
    public Integer getFrontendId() {
        return this.frontendId;
    }

    /**
     * Setter for <code>litdeck.problems.frontend_id</code>.
     */
    public Problemspojo setFrontendId(Integer frontendId) {
        this.frontendId = frontendId;
        return this;
    }

    /**
     * Getter for <code>litdeck.problems.title</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>litdeck.problems.title</code>.
     */
    public Problemspojo setTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * Getter for <code>litdeck.problems.title_slug</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getTitleSlug() {
        return this.titleSlug;
    }

    /**
     * Setter for <code>litdeck.problems.title_slug</code>.
     */
    public Problemspojo setTitleSlug(String titleSlug) {
        this.titleSlug = titleSlug;
        return this;
    }

    /**
     * Getter for <code>litdeck.problems.difficulty</code>.
     */
    @NotNull
    @Size(max = 50)
    public String getDifficulty() {
        return this.difficulty;
    }

    /**
     * Setter for <code>litdeck.problems.difficulty</code>.
     */
    public Problemspojo setDifficulty(String difficulty) {
        this.difficulty = difficulty;
        return this;
    }

    /**
     * Getter for <code>litdeck.problems.is_paid_only</code>.
     */
    @NotNull
    public Byte getIsPaidOnly() {
        return this.isPaidOnly;
    }

    /**
     * Setter for <code>litdeck.problems.is_paid_only</code>.
     */
    public Problemspojo setIsPaidOnly(Byte isPaidOnly) {
        this.isPaidOnly = isPaidOnly;
        return this;
    }

    /**
     * Getter for <code>litdeck.problems.content</code>.
     */
    @NotNull
    @Size(max = 65535)
    public String getContent() {
        return this.content;
    }

    /**
     * Setter for <code>litdeck.problems.content</code>.
     */
    public Problemspojo setContent(String content) {
        this.content = content;
        return this;
    }

    /**
     * Getter for <code>litdeck.problems.topic_tags</code>.
     */
    public JSON getTopicTags() {
        return this.topicTags;
    }

    /**
     * Setter for <code>litdeck.problems.topic_tags</code>.
     */
    public Problemspojo setTopicTags(JSON topicTags) {
        this.topicTags = topicTags;
        return this;
    }

    /**
     * Getter for <code>litdeck.problems.example_testcases</code>.
     */
    @Size(max = 65535)
    public String getExampleTestcases() {
        return this.exampleTestcases;
    }

    /**
     * Setter for <code>litdeck.problems.example_testcases</code>.
     */
    public Problemspojo setExampleTestcases(String exampleTestcases) {
        this.exampleTestcases = exampleTestcases;
        return this;
    }

    /**
     * Getter for <code>litdeck.problems.similar_questions</code>.
     */
    public JSON getSimilarQuestions() {
        return this.similarQuestions;
    }

    /**
     * Setter for <code>litdeck.problems.similar_questions</code>.
     */
    public Problemspojo setSimilarQuestions(JSON similarQuestions) {
        this.similarQuestions = similarQuestions;
        return this;
    }

    /**
     * Getter for <code>litdeck.problems.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>litdeck.problems.created_at</code>.
     */
    public Problemspojo setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Problemspojo other = (Problemspojo) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.frontendId == null) {
            if (other.frontendId != null)
                return false;
        }
        else if (!this.frontendId.equals(other.frontendId))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.titleSlug == null) {
            if (other.titleSlug != null)
                return false;
        }
        else if (!this.titleSlug.equals(other.titleSlug))
            return false;
        if (this.difficulty == null) {
            if (other.difficulty != null)
                return false;
        }
        else if (!this.difficulty.equals(other.difficulty))
            return false;
        if (this.isPaidOnly == null) {
            if (other.isPaidOnly != null)
                return false;
        }
        else if (!this.isPaidOnly.equals(other.isPaidOnly))
            return false;
        if (this.content == null) {
            if (other.content != null)
                return false;
        }
        else if (!this.content.equals(other.content))
            return false;
        if (this.topicTags == null) {
            if (other.topicTags != null)
                return false;
        }
        else if (!this.topicTags.equals(other.topicTags))
            return false;
        if (this.exampleTestcases == null) {
            if (other.exampleTestcases != null)
                return false;
        }
        else if (!this.exampleTestcases.equals(other.exampleTestcases))
            return false;
        if (this.similarQuestions == null) {
            if (other.similarQuestions != null)
                return false;
        }
        else if (!this.similarQuestions.equals(other.similarQuestions))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.frontendId == null) ? 0 : this.frontendId.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.titleSlug == null) ? 0 : this.titleSlug.hashCode());
        result = prime * result + ((this.difficulty == null) ? 0 : this.difficulty.hashCode());
        result = prime * result + ((this.isPaidOnly == null) ? 0 : this.isPaidOnly.hashCode());
        result = prime * result + ((this.content == null) ? 0 : this.content.hashCode());
        result = prime * result + ((this.topicTags == null) ? 0 : this.topicTags.hashCode());
        result = prime * result + ((this.exampleTestcases == null) ? 0 : this.exampleTestcases.hashCode());
        result = prime * result + ((this.similarQuestions == null) ? 0 : this.similarQuestions.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Problemspojo (");

        sb.append(id);
        sb.append(", ").append(frontendId);
        sb.append(", ").append(title);
        sb.append(", ").append(titleSlug);
        sb.append(", ").append(difficulty);
        sb.append(", ").append(isPaidOnly);
        sb.append(", ").append(content);
        sb.append(", ").append(topicTags);
        sb.append(", ").append(exampleTestcases);
        sb.append(", ").append(similarQuestions);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
