/*
 * This file is generated by jOOQ.
 */
package com.ib.jooq.tables.pojos;


import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Topicspojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String name;
    private String slug;
    private LocalDateTime createdAt;

    public Topicspojo() {}

    public Topicspojo(Topicspojo value) {
        this.id = value.id;
        this.name = value.name;
        this.slug = value.slug;
        this.createdAt = value.createdAt;
    }

    public Topicspojo(
        Integer id,
        String name,
        String slug,
        LocalDateTime createdAt
    ) {
        this.id = id;
        this.name = name;
        this.slug = slug;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>litdeck.topics.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>litdeck.topics.id</code>.
     */
    public Topicspojo setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>litdeck.topics.name</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>litdeck.topics.name</code>.
     */
    public Topicspojo setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>litdeck.topics.slug</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getSlug() {
        return this.slug;
    }

    /**
     * Setter for <code>litdeck.topics.slug</code>.
     */
    public Topicspojo setSlug(String slug) {
        this.slug = slug;
        return this;
    }

    /**
     * Getter for <code>litdeck.topics.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>litdeck.topics.created_at</code>.
     */
    public Topicspojo setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Topicspojo other = (Topicspojo) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.slug == null) {
            if (other.slug != null)
                return false;
        }
        else if (!this.slug.equals(other.slug))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.slug == null) ? 0 : this.slug.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Topicspojo (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(slug);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
