/*
 * This file is generated by jOOQ.
 */
package com.ib.jooq.tables.records;


import com.ib.jooq.tables.ReviewLogs;
import com.ib.jooq.tables.pojos.ReviewLogspojo;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReviewLogsRecord extends UpdatableRecordImpl<ReviewLogsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>litdeck.review_logs.id</code>.
     */
    public ReviewLogsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_logs.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>litdeck.review_logs.user_id</code>.
     */
    public ReviewLogsRecord setUserId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_logs.user_id</code>.
     */
    @NotNull
    @Size(max = 36)
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>litdeck.review_logs.problem_id</code>.
     */
    public ReviewLogsRecord setProblemId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_logs.problem_id</code>.
     */
    @NotNull
    public Integer getProblemId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>litdeck.review_logs.rating</code>.
     */
    public ReviewLogsRecord setRating(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_logs.rating</code>.
     */
    @NotNull
    public Integer getRating() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>litdeck.review_logs.state</code>.
     */
    public ReviewLogsRecord setState(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_logs.state</code>.
     */
    @NotNull
    @Size(max = 50)
    public String getState() {
        return (String) get(4);
    }

    /**
     * Setter for <code>litdeck.review_logs.due_date</code>.
     */
    public ReviewLogsRecord setDueDate(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_logs.due_date</code>.
     */
    @NotNull
    public LocalDateTime getDueDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>litdeck.review_logs.stability</code>.
     */
    public ReviewLogsRecord setStability(Double value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_logs.stability</code>.
     */
    @NotNull
    public Double getStability() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>litdeck.review_logs.difficulty</code>.
     */
    public ReviewLogsRecord setDifficulty(Double value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_logs.difficulty</code>.
     */
    @NotNull
    public Double getDifficulty() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>litdeck.review_logs.elapsed_days</code>.
     */
    public ReviewLogsRecord setElapsedDays(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_logs.elapsed_days</code>.
     */
    @NotNull
    public Integer getElapsedDays() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>litdeck.review_logs.last_elapsed_days</code>.
     */
    public ReviewLogsRecord setLastElapsedDays(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_logs.last_elapsed_days</code>.
     */
    @NotNull
    public Integer getLastElapsedDays() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>litdeck.review_logs.scheduled_days</code>.
     */
    public ReviewLogsRecord setScheduledDays(Integer value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_logs.scheduled_days</code>.
     */
    @NotNull
    public Integer getScheduledDays() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>litdeck.review_logs.review_date</code>.
     */
    public ReviewLogsRecord setReviewDate(LocalDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_logs.review_date</code>.
     */
    @NotNull
    public LocalDateTime getReviewDate() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>litdeck.review_logs.created_at</code>.
     */
    public ReviewLogsRecord setCreatedAt(LocalDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_logs.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReviewLogsRecord
     */
    public ReviewLogsRecord() {
        super(ReviewLogs.REVIEW_LOGS);
    }

    /**
     * Create a detached, initialised ReviewLogsRecord
     */
    public ReviewLogsRecord(Integer id, String userId, Integer problemId, Integer rating, String state, LocalDateTime dueDate, Double stability, Double difficulty, Integer elapsedDays, Integer lastElapsedDays, Integer scheduledDays, LocalDateTime reviewDate, LocalDateTime createdAt) {
        super(ReviewLogs.REVIEW_LOGS);

        setId(id);
        setUserId(userId);
        setProblemId(problemId);
        setRating(rating);
        setState(state);
        setDueDate(dueDate);
        setStability(stability);
        setDifficulty(difficulty);
        setElapsedDays(elapsedDays);
        setLastElapsedDays(lastElapsedDays);
        setScheduledDays(scheduledDays);
        setReviewDate(reviewDate);
        setCreatedAt(createdAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised ReviewLogsRecord
     */
    public ReviewLogsRecord(ReviewLogspojo value) {
        super(ReviewLogs.REVIEW_LOGS);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setProblemId(value.getProblemId());
            setRating(value.getRating());
            setState(value.getState());
            setDueDate(value.getDueDate());
            setStability(value.getStability());
            setDifficulty(value.getDifficulty());
            setElapsedDays(value.getElapsedDays());
            setLastElapsedDays(value.getLastElapsedDays());
            setScheduledDays(value.getScheduledDays());
            setReviewDate(value.getReviewDate());
            setCreatedAt(value.getCreatedAt());
            resetTouchedOnNotNull();
        }
    }
}
