/*
 * This file is generated by jOOQ.
 */
package com.ib.jooq.tables.records;


import com.ib.jooq.tables.ReviewSchedules;
import com.ib.jooq.tables.pojos.ReviewSchedulespojo;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReviewSchedulesRecord extends UpdatableRecordImpl<ReviewSchedulesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>litdeck.review_schedules.id</code>.
     */
    public ReviewSchedulesRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>litdeck.review_schedules.user_id</code>.
     */
    public ReviewSchedulesRecord setUserId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.user_id</code>.
     */
    @NotNull
    @Size(max = 36)
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>litdeck.review_schedules.problem_id</code>.
     */
    public ReviewSchedulesRecord setProblemId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.problem_id</code>.
     */
    @NotNull
    public Integer getProblemId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>litdeck.review_schedules.due_date</code>.
     */
    public ReviewSchedulesRecord setDueDate(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.due_date</code>.
     */
    @NotNull
    public LocalDateTime getDueDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>litdeck.review_schedules.stability</code>.
     */
    public ReviewSchedulesRecord setStability(Double value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.stability</code>.
     */
    public Double getStability() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>litdeck.review_schedules.difficulty</code>.
     */
    public ReviewSchedulesRecord setDifficulty(Double value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.difficulty</code>.
     */
    public Double getDifficulty() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>litdeck.review_schedules.elapsed_days</code>.
     */
    public ReviewSchedulesRecord setElapsedDays(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.elapsed_days</code>.
     */
    public Integer getElapsedDays() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>litdeck.review_schedules.scheduled_days</code>.
     */
    public ReviewSchedulesRecord setScheduledDays(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.scheduled_days</code>.
     */
    public Integer getScheduledDays() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>litdeck.review_schedules.reps</code>.
     */
    public ReviewSchedulesRecord setReps(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.reps</code>.
     */
    public Integer getReps() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>litdeck.review_schedules.lapses</code>.
     */
    public ReviewSchedulesRecord setLapses(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.lapses</code>.
     */
    public Integer getLapses() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>litdeck.review_schedules.state</code>.
     */
    public ReviewSchedulesRecord setState(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.state</code>.
     */
    @Size(max = 50)
    public String getState() {
        return (String) get(10);
    }

    /**
     * Setter for <code>litdeck.review_schedules.last_review</code>.
     */
    public ReviewSchedulesRecord setLastReview(LocalDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.last_review</code>.
     */
    public LocalDateTime getLastReview() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>litdeck.review_schedules.created_at</code>.
     */
    public ReviewSchedulesRecord setCreatedAt(LocalDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>litdeck.review_schedules.updated_at</code>.
     */
    public ReviewSchedulesRecord setUpdatedAt(LocalDateTime value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.review_schedules.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReviewSchedulesRecord
     */
    public ReviewSchedulesRecord() {
        super(ReviewSchedules.REVIEW_SCHEDULES);
    }

    /**
     * Create a detached, initialised ReviewSchedulesRecord
     */
    public ReviewSchedulesRecord(Integer id, String userId, Integer problemId, LocalDateTime dueDate, Double stability, Double difficulty, Integer elapsedDays, Integer scheduledDays, Integer reps, Integer lapses, String state, LocalDateTime lastReview, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(ReviewSchedules.REVIEW_SCHEDULES);

        setId(id);
        setUserId(userId);
        setProblemId(problemId);
        setDueDate(dueDate);
        setStability(stability);
        setDifficulty(difficulty);
        setElapsedDays(elapsedDays);
        setScheduledDays(scheduledDays);
        setReps(reps);
        setLapses(lapses);
        setState(state);
        setLastReview(lastReview);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised ReviewSchedulesRecord
     */
    public ReviewSchedulesRecord(ReviewSchedulespojo value) {
        super(ReviewSchedules.REVIEW_SCHEDULES);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setProblemId(value.getProblemId());
            setDueDate(value.getDueDate());
            setStability(value.getStability());
            setDifficulty(value.getDifficulty());
            setElapsedDays(value.getElapsedDays());
            setScheduledDays(value.getScheduledDays());
            setReps(value.getReps());
            setLapses(value.getLapses());
            setState(value.getState());
            setLastReview(value.getLastReview());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetTouchedOnNotNull();
        }
    }
}
