/*
 * This file is generated by jOOQ.
 */
package com.ib.jooq.tables.records;


import com.ib.jooq.tables.Solutions;
import com.ib.jooq.tables.pojos.Solutionspojo;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SolutionsRecord extends UpdatableRecordImpl<SolutionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>litdeck.solutions.id</code>.
     */
    public SolutionsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.solutions.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>litdeck.solutions.problem_id</code>.
     */
    public SolutionsRecord setProblemId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.solutions.problem_id</code>.
     */
    @NotNull
    public Integer getProblemId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>litdeck.solutions.title</code>.
     */
    public SolutionsRecord setTitle(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.solutions.title</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>litdeck.solutions.language</code>.
     */
    public SolutionsRecord setLanguage(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.solutions.language</code>.
     */
    @NotNull
    @Size(max = 50)
    public String getLanguage() {
        return (String) get(3);
    }

    /**
     * Setter for <code>litdeck.solutions.code</code>.
     */
    public SolutionsRecord setCode(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.solutions.code</code>.
     */
    @NotNull
    @Size(max = 65535)
    public String getCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>litdeck.solutions.explanation</code>.
     */
    public SolutionsRecord setExplanation(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.solutions.explanation</code>.
     */
    @Size(max = 65535)
    public String getExplanation() {
        return (String) get(5);
    }

    /**
     * Setter for <code>litdeck.solutions.time_complexity</code>.
     */
    public SolutionsRecord setTimeComplexity(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.solutions.time_complexity</code>.
     */
    @Size(max = 100)
    public String getTimeComplexity() {
        return (String) get(6);
    }

    /**
     * Setter for <code>litdeck.solutions.space_complexity</code>.
     */
    public SolutionsRecord setSpaceComplexity(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.solutions.space_complexity</code>.
     */
    @Size(max = 100)
    public String getSpaceComplexity() {
        return (String) get(7);
    }

    /**
     * Setter for <code>litdeck.solutions.is_optimal</code>.
     */
    public SolutionsRecord setIsOptimal(Byte value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.solutions.is_optimal</code>.
     */
    public Byte getIsOptimal() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>litdeck.solutions.created_at</code>.
     */
    public SolutionsRecord setCreatedAt(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.solutions.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>litdeck.solutions.updated_at</code>.
     */
    public SolutionsRecord setUpdatedAt(LocalDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.solutions.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SolutionsRecord
     */
    public SolutionsRecord() {
        super(Solutions.SOLUTIONS);
    }

    /**
     * Create a detached, initialised SolutionsRecord
     */
    public SolutionsRecord(Integer id, Integer problemId, String title, String language, String code, String explanation, String timeComplexity, String spaceComplexity, Byte isOptimal, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Solutions.SOLUTIONS);

        setId(id);
        setProblemId(problemId);
        setTitle(title);
        setLanguage(language);
        setCode(code);
        setExplanation(explanation);
        setTimeComplexity(timeComplexity);
        setSpaceComplexity(spaceComplexity);
        setIsOptimal(isOptimal);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised SolutionsRecord
     */
    public SolutionsRecord(Solutionspojo value) {
        super(Solutions.SOLUTIONS);

        if (value != null) {
            setId(value.getId());
            setProblemId(value.getProblemId());
            setTitle(value.getTitle());
            setLanguage(value.getLanguage());
            setCode(value.getCode());
            setExplanation(value.getExplanation());
            setTimeComplexity(value.getTimeComplexity());
            setSpaceComplexity(value.getSpaceComplexity());
            setIsOptimal(value.getIsOptimal());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetTouchedOnNotNull();
        }
    }
}
