/*
 * This file is generated by jOOQ.
 */
package com.ib.jooq.tables.records;


import com.ib.jooq.tables.Submissions;
import com.ib.jooq.tables.pojos.Submissionspojo;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SubmissionsRecord extends UpdatableRecordImpl<SubmissionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>litdeck.submissions.id</code>.
     */
    public SubmissionsRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.submissions.id</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>litdeck.submissions.title</code>.
     */
    public SubmissionsRecord setTitle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.submissions.title</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>litdeck.submissions.title_slug</code>.
     */
    public SubmissionsRecord setTitleSlug(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.submissions.title_slug</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getTitleSlug() {
        return (String) get(2);
    }

    /**
     * Setter for <code>litdeck.submissions.submitted_at</code>.
     */
    public SubmissionsRecord setSubmittedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.submissions.submitted_at</code>.
     */
    @NotNull
    public LocalDateTime getSubmittedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>litdeck.submissions.created_at</code>.
     */
    public SubmissionsRecord setCreatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.submissions.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>litdeck.submissions.user_id</code>.
     */
    public SubmissionsRecord setUserId(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.submissions.user_id</code>.
     */
    @NotNull
    @Size(max = 36)
    public String getUserId() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubmissionsRecord
     */
    public SubmissionsRecord() {
        super(Submissions.SUBMISSIONS);
    }

    /**
     * Create a detached, initialised SubmissionsRecord
     */
    public SubmissionsRecord(String id, String title, String titleSlug, LocalDateTime submittedAt, LocalDateTime createdAt, String userId) {
        super(Submissions.SUBMISSIONS);

        setId(id);
        setTitle(title);
        setTitleSlug(titleSlug);
        setSubmittedAt(submittedAt);
        setCreatedAt(createdAt);
        setUserId(userId);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised SubmissionsRecord
     */
    public SubmissionsRecord(Submissionspojo value) {
        super(Submissions.SUBMISSIONS);

        if (value != null) {
            setId(value.getId());
            setTitle(value.getTitle());
            setTitleSlug(value.getTitleSlug());
            setSubmittedAt(value.getSubmittedAt());
            setCreatedAt(value.getCreatedAt());
            setUserId(value.getUserId());
            resetTouchedOnNotNull();
        }
    }
}
