/*
 * This file is generated by jOOQ.
 */
package com.ib.jooq.tables.records;


import com.ib.jooq.tables.Topics;
import com.ib.jooq.tables.pojos.Topicspojo;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TopicsRecord extends UpdatableRecordImpl<TopicsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>litdeck.topics.id</code>.
     */
    public TopicsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.topics.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>litdeck.topics.name</code>.
     */
    public TopicsRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.topics.name</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>litdeck.topics.slug</code>.
     */
    public TopicsRecord setSlug(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.topics.slug</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getSlug() {
        return (String) get(2);
    }

    /**
     * Setter for <code>litdeck.topics.created_at</code>.
     */
    public TopicsRecord setCreatedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>litdeck.topics.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TopicsRecord
     */
    public TopicsRecord() {
        super(Topics.TOPICS);
    }

    /**
     * Create a detached, initialised TopicsRecord
     */
    public TopicsRecord(Integer id, String name, String slug, LocalDateTime createdAt) {
        super(Topics.TOPICS);

        setId(id);
        setName(name);
        setSlug(slug);
        setCreatedAt(createdAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised TopicsRecord
     */
    public TopicsRecord(Topicspojo value) {
        super(Topics.TOPICS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setSlug(value.getSlug());
            setCreatedAt(value.getCreatedAt());
            resetTouchedOnNotNull();
        }
    }
}
